import { AnalyticsArticle } from './types';
import { getAuthorAvatar, categoryImages } from './utils';

// Simplified analytics data for fast loading
const quickAnalytics: AnalyticsArticle[] = [
  // Christina Summerbell - Technology & Growth Stocks
  {
    slug: 'etf-strategies-wealth-building',
    title: 'ETF Strategies for Long-Term Wealth Building',
    excerpt: 'Comprehensive guide to building a diversified ETF portfolio that grows over time.',
    content: 'Exchange-traded funds (ETFs) have revolutionized investing...',
    date: '2024-12-10',
    author: 'Christina Summerbell',
    authorAvatar: getAuthorAvatar('Christina Summerbell'),
    type: 'longterm',
    readTime: '14 min',
    imageUrl: categoryImages.longterm[0],
    tags: ['ETF', 'Portfolio', 'Diversification'],
  },
  {
    slug: 'tech-stocks-2025-outlook',
    title: 'Tech Stocks 2025: AI Revolution Continues',
    excerpt: 'Analyzing the next wave of technology investments as AI transforms industries.',
    content: 'The technology sector continues to lead market innovation...',
    date: '2024-12-08',
    author: 'Christina Summerbell',
    authorAvatar: getAuthorAvatar('Christina Summerbell'),
    type: 'markets',
    readTime: '12 min',
    imageUrl: categoryImages.markets[0],
    tags: ['Tech', 'AI', 'Growth'],
  },
  {
    slug: 'growth-investing-fundamentals',
    title: 'Growth Investing: Finding Tomorrow\'s Winners',
    excerpt: 'Key metrics and strategies for identifying high-growth opportunities.',
    content: 'Growth investing focuses on companies with above-average growth potential...',
    date: '2024-11-28',
    author: 'Christina Summerbell',
    authorAvatar: getAuthorAvatar('Christina Summerbell'),
    type: 'expert',
    readTime: '11 min',
    imageUrl: categoryImages.expert[0],
    tags: ['Growth', 'Strategy', 'Analysis'],
  },
  {
    slug: 'semiconductor-industry-analysis',
    title: 'Semiconductor Industry: Supply Chain Recovery',
    excerpt: 'Deep dive into chip makers and the evolving semiconductor landscape.',
    content: 'The semiconductor industry has undergone significant transformation...',
    date: '2024-11-15',
    author: 'Christina Summerbell',
    authorAvatar: getAuthorAvatar('Christina Summerbell'),
    type: 'technical',
    readTime: '15 min',
    imageUrl: categoryImages.technical[0],
    tags: ['Semiconductors', 'Tech', 'Analysis'],
  },

  // Assunta Novak - Crypto & Blockchain
  {
    slug: 'cryptocurrency-fundamentals',
    title: 'Cryptocurrency Fundamentals: Beyond Bitcoin',
    excerpt: 'Understanding the diverse world of digital assets and blockchain technology.',
    content: 'The cryptocurrency ecosystem has evolved far beyond Bitcoin...',
    date: '2024-12-05',
    author: 'Assunta Novak',
    authorAvatar: getAuthorAvatar('Assunta Novak'),
    type: 'markets',
    readTime: '13 min',
    imageUrl: categoryImages.markets[1],
    tags: ['Crypto', 'Bitcoin', 'Blockchain'],
  },
  {
    slug: 'defi-revolution-2025',
    title: 'DeFi Revolution: Decentralized Finance Matures',
    excerpt: 'How decentralized finance is reshaping traditional banking and lending.',
    content: 'Decentralized finance has grown from a niche experiment...',
    date: '2024-12-01',
    author: 'Assunta Novak',
    authorAvatar: getAuthorAvatar('Assunta Novak'),
    type: 'expert',
    readTime: '14 min',
    imageUrl: categoryImages.expert[1],
    tags: ['DeFi', 'Crypto', 'Finance'],
  },
  {
    slug: 'bitcoin-halving-analysis',
    title: 'Bitcoin Halving: Historical Patterns and Predictions',
    excerpt: 'Analyzing past halvings to predict future Bitcoin price movements.',
    content: 'Bitcoin halving events have historically triggered significant price action...',
    date: '2024-11-20',
    author: 'Assunta Novak',
    authorAvatar: getAuthorAvatar('Assunta Novak'),
    type: 'technical',
    readTime: '10 min',
    imageUrl: categoryImages.technical[1],
    tags: ['Bitcoin', 'Halving', 'Technical'],
  },
  {
    slug: 'stablecoin-ecosystem-guide',
    title: 'Stablecoin Ecosystem: Safety and Yield Strategies',
    excerpt: 'Navigating the world of stablecoins for stability and passive income.',
    content: 'Stablecoins have become a cornerstone of the crypto ecosystem...',
    date: '2024-11-05',
    author: 'Assunta Novak',
    authorAvatar: getAuthorAvatar('Assunta Novak'),
    type: 'longterm',
    readTime: '11 min',
    imageUrl: categoryImages.longterm[1],
    tags: ['Stablecoins', 'Yield', 'Crypto'],
  },

  // Lysander Truog - Fixed Income & Bonds
  {
    slug: 'dividend-investing-passive-income',
    title: 'Dividend Investing: Building Passive Income Streams',
    excerpt: 'How to identify and invest in quality dividend-paying stocks for steady income.',
    content: 'Dividend investing remains one of the most reliable strategies...',
    date: '2024-12-09',
    author: 'Lysander Truog',
    authorAvatar: getAuthorAvatar('Lysander Truog'),
    type: 'expert',
    readTime: '12 min',
    imageUrl: categoryImages.expert[2],
    tags: ['Dividends', 'Income', 'Stocks'],
  },
  {
    slug: 'bond-market-outlook-2025',
    title: 'Bond Market Outlook: Interest Rate Trajectory',
    excerpt: 'Analyzing central bank policies and their impact on fixed income investments.',
    content: 'The bond market faces significant shifts as central banks navigate...',
    date: '2024-12-03',
    author: 'Lysander Truog',
    authorAvatar: getAuthorAvatar('Lysander Truog'),
    type: 'markets',
    readTime: '13 min',
    imageUrl: categoryImages.markets[2],
    tags: ['Bonds', 'Interest Rates', 'Fed'],
  },
  {
    slug: 'treasury-bonds-safe-haven',
    title: 'Treasury Bonds: The Ultimate Safe Haven',
    excerpt: 'Understanding government bonds as portfolio stabilizers during volatility.',
    content: 'Treasury bonds have long been considered the safest investments...',
    date: '2024-11-18',
    author: 'Lysander Truog',
    authorAvatar: getAuthorAvatar('Lysander Truog'),
    type: 'longterm',
    readTime: '9 min',
    imageUrl: categoryImages.longterm[2],
    tags: ['Treasury', 'Bonds', 'Safety'],
  },

  // Elias Wolfenstein - European Markets & M&A
  {
    slug: 'european-markets-recovery',
    title: 'European Markets: Post-Crisis Recovery Analysis',
    excerpt: 'Examining the resilience and opportunities in European equity markets.',
    content: 'European markets have shown remarkable resilience...',
    date: '2024-12-07',
    author: 'Elias Wolfenstein',
    authorAvatar: getAuthorAvatar('Elias Wolfenstein'),
    type: 'markets',
    readTime: '14 min',
    imageUrl: categoryImages.markets[3],
    tags: ['Europe', 'Recovery', 'Markets'],
  },
  {
    slug: 'ma-trends-2025',
    title: 'M&A Trends: Cross-Border Deals Surge',
    excerpt: 'Key merger and acquisition trends shaping the corporate landscape.',
    content: 'Merger and acquisition activity has reached unprecedented levels...',
    date: '2024-11-30',
    author: 'Elias Wolfenstein',
    authorAvatar: getAuthorAvatar('Elias Wolfenstein'),
    type: 'expert',
    readTime: '11 min',
    imageUrl: categoryImages.expert[3],
    tags: ['M&A', 'Corporate', 'Strategy'],
  },
  {
    slug: 'german-dax-analysis',
    title: 'German DAX: Industrial Powerhouse Returns',
    excerpt: 'Technical and fundamental analysis of Germany\'s premier stock index.',
    content: 'The DAX index represents Germany\'s economic strength...',
    date: '2024-11-12',
    author: 'Elias Wolfenstein',
    authorAvatar: getAuthorAvatar('Elias Wolfenstein'),
    type: 'technical',
    readTime: '12 min',
    imageUrl: categoryImages.technical[2],
    tags: ['DAX', 'Germany', 'Technical'],
  },
  {
    slug: 'eu-banking-sector-outlook',
    title: 'EU Banking Sector: Consolidation Accelerates',
    excerpt: 'Analyzing European bank mergers and regulatory changes.',
    content: 'European banks face a transformative period...',
    date: '2024-10-28',
    author: 'Elias Wolfenstein',
    authorAvatar: getAuthorAvatar('Elias Wolfenstein'),
    type: 'expert',
    readTime: '13 min',
    imageUrl: categoryImages.expert[4],
    tags: ['Banking', 'Europe', 'Finance'],
  },

  // Anastasia Petrova - Emerging Markets & Energy
  {
    slug: 'emerging-markets-opportunity',
    title: 'Emerging Markets: Hidden Gems for 2025',
    excerpt: 'Discovering undervalued opportunities in developing economies.',
    content: 'Emerging markets offer compelling valuations...',
    date: '2024-12-06',
    author: 'Anastasia Petrova',
    authorAvatar: getAuthorAvatar('Anastasia Petrova'),
    type: 'markets',
    readTime: '15 min',
    imageUrl: categoryImages.markets[4],
    tags: ['Emerging', 'Markets', 'Opportunity'],
  },
  {
    slug: 'energy-sector-transition',
    title: 'Energy Sector: Traditional vs Renewable Dynamics',
    excerpt: 'Balancing oil & gas investments with renewable energy exposure.',
    content: 'The energy sector is undergoing a historic transformation...',
    date: '2024-11-25',
    author: 'Anastasia Petrova',
    authorAvatar: getAuthorAvatar('Anastasia Petrova'),
    type: 'expert',
    readTime: '14 min',
    imageUrl: categoryImages.expert[5],
    tags: ['Energy', 'Oil', 'Renewables'],
  },
  {
    slug: 'eastern-europe-growth',
    title: 'Eastern Europe: Economic Growth Accelerates',
    excerpt: 'Investment opportunities in Poland, Czech Republic, and beyond.',
    content: 'Eastern European economies continue to outperform...',
    date: '2024-11-08',
    author: 'Anastasia Petrova',
    authorAvatar: getAuthorAvatar('Anastasia Petrova'),
    type: 'longterm',
    readTime: '12 min',
    imageUrl: categoryImages.longterm[3],
    tags: ['Eastern Europe', 'Growth', 'Investment'],
  },

  // Luca Montefiore - Luxury & Mediterranean Markets
  {
    slug: 'risk-management-portfolio',
    title: 'Risk Management Strategies for Your Portfolio',
    excerpt: 'Learn how to protect your investments while maximizing returns.',
    content: 'Effective risk management is the cornerstone of successful investing...',
    date: '2024-12-04',
    author: 'Luca Montefiore',
    authorAvatar: getAuthorAvatar('Luca Montefiore'),
    type: 'expert',
    readTime: '11 min',
    imageUrl: categoryImages.expert[0],
    tags: ['Risk', 'Portfolio', 'Strategy'],
  },
  {
    slug: 'luxury-brands-investment',
    title: 'Luxury Brands: Recession-Proof Investments',
    excerpt: 'Why premium consumer goods companies outperform in turbulent times.',
    content: 'Luxury brand stocks have historically demonstrated resilience...',
    date: '2024-11-22',
    author: 'Luca Montefiore',
    authorAvatar: getAuthorAvatar('Luca Montefiore'),
    type: 'markets',
    readTime: '10 min',
    imageUrl: categoryImages.markets[5],
    tags: ['Luxury', 'Consumer', 'Brands'],
  },
  {
    slug: 'italian-market-renaissance',
    title: 'Italian Markets: A New Renaissance',
    excerpt: 'Exploring investment opportunities in Italy\'s evolving economy.',
    content: 'Italy\'s market has undergone significant structural reforms...',
    date: '2024-10-30',
    author: 'Luca Montefiore',
    authorAvatar: getAuthorAvatar('Luca Montefiore'),
    type: 'longterm',
    readTime: '13 min',
    imageUrl: categoryImages.longterm[4],
    tags: ['Italy', 'Europe', 'Markets'],
  },

  // Isabelle Dubois - ESG & Sustainable Finance
  {
    slug: 'esg-investing-guide',
    title: 'ESG Investing: Performance Meets Purpose',
    excerpt: 'How environmental, social, and governance factors drive returns.',
    content: 'ESG investing has moved from niche to mainstream...',
    date: '2024-12-02',
    author: 'Isabelle Dubois',
    authorAvatar: getAuthorAvatar('Isabelle Dubois'),
    type: 'expert',
    readTime: '14 min',
    imageUrl: categoryImages.expert[1],
    tags: ['ESG', 'Sustainable', 'Investing'],
  },
  {
    slug: 'green-bonds-explained',
    title: 'Green Bonds: Financing the Climate Transition',
    excerpt: 'Understanding the growing market for environmentally-focused debt.',
    content: 'Green bonds have emerged as a crucial financing mechanism...',
    date: '2024-11-27',
    author: 'Isabelle Dubois',
    authorAvatar: getAuthorAvatar('Isabelle Dubois'),
    type: 'longterm',
    readTime: '11 min',
    imageUrl: categoryImages.longterm[5],
    tags: ['Green Bonds', 'Climate', 'Fixed Income'],
  },
  {
    slug: 'impact-investing-strategies',
    title: 'Impact Investing: Measurable Social Returns',
    excerpt: 'Strategies for achieving both financial and social impact goals.',
    content: 'Impact investing seeks to generate positive social outcomes...',
    date: '2024-11-10',
    author: 'Isabelle Dubois',
    authorAvatar: getAuthorAvatar('Isabelle Dubois'),
    type: 'expert',
    readTime: '12 min',
    imageUrl: categoryImages.expert[2],
    tags: ['Impact', 'Social', 'Returns'],
  },
  {
    slug: 'carbon-credit-markets',
    title: 'Carbon Credit Markets: Investment Frontier',
    excerpt: 'Navigating the emerging opportunities in carbon trading.',
    content: 'Carbon credit markets have evolved into investable assets...',
    date: '2024-10-20',
    author: 'Isabelle Dubois',
    authorAvatar: getAuthorAvatar('Isabelle Dubois'),
    type: 'markets',
    readTime: '10 min',
    imageUrl: categoryImages.markets[0],
    tags: ['Carbon', 'Climate', 'Trading'],
  },

  // Xu Meiling - Asia-Pacific & Chinese Markets
  {
    slug: 'market-outlook-2025',
    title: 'Market Outlook 2025: What Investors Should Expect',
    excerpt: 'Expert predictions and analysis for the coming year in global markets.',
    content: 'As we approach 2025, several key trends are shaping the investment landscape...',
    date: '2024-12-09',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'markets',
    readTime: '10 min',
    imageUrl: categoryImages.markets[0],
    tags: ['Markets', 'Outlook', '2025'],
  },
  {
    slug: 'technical-analysis-fundamentals',
    title: 'Technical Analysis: Chart Patterns and Indicators',
    excerpt: 'Master the essential technical analysis tools used by professional traders.',
    content: 'Technical analysis involves analyzing statistical trends...',
    date: '2024-12-08',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'technical',
    readTime: '15 min',
    imageUrl: categoryImages.technical[0],
    tags: ['Technical Analysis', 'Charts', 'Trading'],
  },
  {
    slug: 'china-equities-analysis',
    title: 'China Equities: Navigating Regulatory Changes',
    excerpt: 'Strategic approach to Chinese stocks amid policy shifts.',
    content: 'Chinese equity markets present unique opportunities...',
    date: '2024-11-29',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'markets',
    readTime: '13 min',
    imageUrl: categoryImages.markets[1],
    tags: ['China', 'Equities', 'Regulation'],
  },
  {
    slug: 'asian-tech-giants',
    title: 'Asian Tech Giants: Beyond FAANG',
    excerpt: 'Discovering Asia\'s technology leaders and their growth potential.',
    content: 'Asian technology companies are challenging Western dominance...',
    date: '2024-11-14',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'expert',
    readTime: '14 min',
    imageUrl: categoryImages.expert[3],
    tags: ['Asia', 'Tech', 'Growth'],
  },
  {
    slug: 'japan-market-revival',
    title: 'Japan Market Revival: Corporate Governance Reforms',
    excerpt: 'How Japanese companies are unlocking shareholder value.',
    content: 'Japan\'s corporate governance revolution has transformed...',
    date: '2024-10-25',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'longterm',
    readTime: '12 min',
    imageUrl: categoryImages.longterm[0],
    tags: ['Japan', 'Governance', 'Value'],
  },
  {
    slug: 'apac-real-estate-trends',
    title: 'APAC Real Estate: Investment Trends and Opportunities',
    excerpt: 'Analyzing property markets across Asia-Pacific for portfolio diversification.',
    content: 'Asia-Pacific real estate markets offer diverse opportunities...',
    date: '2024-10-15',
    author: 'Xu Meiling',
    authorAvatar: getAuthorAvatar('Xu Meiling'),
    type: 'expert',
    readTime: '11 min',
    imageUrl: categoryImages.expert[4],
    tags: ['Real Estate', 'APAC', 'Investment'],
  },
];

export async function fetchAnalytics(type?: string): Promise<AnalyticsArticle[]> {
  let result = [...quickAnalytics];
  
  if (type && type !== 'all') {
    result = result.filter(item => item.type === type);
  }
  
  return result;
}

export async function fetchAnalyticsBySlug(slug: string): Promise<AnalyticsArticle | null> {
  // Try to find in quick analytics first
  const found = quickAnalytics.find(item => item.slug === slug);
  if (found) return found;
  
  // If not found, dynamically import full analytics from api.ts
  try {
    const { fetchAnalyticsBySlug: fullFetch } = await import('../api');
    return fullFetch(slug);
  } catch {
    return null;
  }
}
