// Financial Organizations Data - 400+ Global Organizations

export type OrganizationType = 'broker' | 'hedge_fund' | 'bank' | 'asset_manager' | 'wealth_manager' | 'pension_fund';

export type Region = 'north_america' | 'europe' | 'asia_pacific' | 'middle_east_africa' | 'latin_america' | 'global';

export interface Organization {
  id: string;
  name: string;
  logo?: string;
  type: OrganizationType;
  region: Region;
  description: string;
  founded: string;
  headquarters: string;
  aum?: string;
  employees?: string;
  communityTrust: number;
  expertTrust: number;
  website?: string;
  regulated: boolean;
  regulators?: string[];
}

export const organizations: Organization[] = [
  // ===== NORTH AMERICA =====
  // US Brokers
  { id: 'interactive-brokers', name: 'Interactive Brokers', logo: 'https://logo.clearbit.com/interactivebrokers.com', type: 'broker', region: 'north_america', description: 'Professional-grade brokerage with low commissions and global market access.', founded: '1978', headquarters: 'Greenwich, CT', employees: '3,000+', communityTrust: 92, expertTrust: 95, regulated: true, regulators: ['SEC', 'FINRA', 'FCA'] },
  { id: 'charles-schwab', name: 'Charles Schwab', logo: 'https://logo.clearbit.com/schwab.com', type: 'broker', region: 'north_america', description: 'Full-service brokerage and banking with commission-free trading.', founded: '1971', headquarters: 'Westlake, TX', employees: '36,000+', communityTrust: 89, expertTrust: 91, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'fidelity', name: 'Fidelity Investments', logo: 'https://logo.clearbit.com/fidelity.com', type: 'broker', region: 'north_america', description: 'Leading brokerage with excellent research and retirement services.', founded: '1946', headquarters: 'Boston, MA', aum: '$4.5T', employees: '74,000+', communityTrust: 91, expertTrust: 94, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'td-ameritrade', name: 'TD Ameritrade', logo: 'https://logo.clearbit.com/tdameritrade.com', type: 'broker', region: 'north_america', description: 'Popular broker known for thinkorswim trading platform.', founded: '1975', headquarters: 'Omaha, NE', employees: '10,000+', communityTrust: 85, expertTrust: 88, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'robinhood', name: 'Robinhood', logo: 'https://logo.clearbit.com/robinhood.com', type: 'broker', region: 'north_america', description: 'Commission-free trading app popular with retail investors.', founded: '2013', headquarters: 'Menlo Park, CA', employees: '2,300+', communityTrust: 62, expertTrust: 58, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'etrade', name: 'E*TRADE', logo: 'https://logo.clearbit.com/etrade.com', type: 'broker', region: 'north_america', description: 'Online brokerage with strong options trading platform.', founded: '1982', headquarters: 'Arlington, VA', employees: '4,500+', communityTrust: 84, expertTrust: 86, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'webull', name: 'Webull', logo: 'https://logo.clearbit.com/webull.com', type: 'broker', region: 'north_america', description: 'Commission-free trading with advanced charting tools.', founded: '2017', headquarters: 'New York, NY', employees: '1,000+', communityTrust: 72, expertTrust: 68, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'tastytrade', name: 'Tastytrade', logo: 'https://logo.clearbit.com/tastytrade.com', type: 'broker', region: 'north_america', description: 'Options-focused broker with educational content.', founded: '2017', headquarters: 'Chicago, IL', employees: '500+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'ally-invest', name: 'Ally Invest', logo: 'https://logo.clearbit.com/ally.com', type: 'broker', region: 'north_america', description: 'Online broker integrated with Ally Bank services.', founded: '2005', headquarters: 'Charlotte, NC', employees: '11,000+', communityTrust: 76, expertTrust: 78, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'merrill-edge', name: 'Merrill Edge', logo: 'https://logo.clearbit.com/merrilledge.com', type: 'broker', region: 'north_america', description: 'Bank of America integrated investment platform.', founded: '2010', headquarters: 'Charlotte, NC', employees: '15,000+', communityTrust: 82, expertTrust: 85, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'vanguard-brokerage', name: 'Vanguard Brokerage', logo: 'https://logo.clearbit.com/vanguard.com', type: 'broker', region: 'north_america', description: 'Low-cost brokerage focused on long-term investors.', founded: '1975', headquarters: 'Malvern, PA', employees: '20,000+', communityTrust: 94, expertTrust: 96, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'sofi-invest', name: 'SoFi Invest', logo: 'https://logo.clearbit.com/sofi.com', type: 'broker', region: 'north_america', description: 'Modern brokerage with fractional shares.', founded: '2011', headquarters: 'San Francisco, CA', employees: '5,000+', communityTrust: 70, expertTrust: 65, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'public', name: 'Public.com', logo: 'https://logo.clearbit.com/public.com', type: 'broker', region: 'north_america', description: 'Social investing platform with community features.', founded: '2019', headquarters: 'New York, NY', employees: '400+', communityTrust: 68, expertTrust: 62, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'tradestation', name: 'TradeStation', logo: 'https://logo.clearbit.com/tradestation.com', type: 'broker', region: 'north_america', description: 'Advanced trading platform for active traders.', founded: '1982', headquarters: 'Plantation, FL', employees: '600+', communityTrust: 80, expertTrust: 84, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'firstrade', name: 'Firstrade', logo: 'https://logo.clearbit.com/firstrade.com', type: 'broker', region: 'north_america', description: 'Commission-free broker with options trading.', founded: '1985', headquarters: 'Flushing, NY', employees: '200+', communityTrust: 74, expertTrust: 72, regulated: true, regulators: ['SEC', 'FINRA'] },

  // Canada Brokers & Banks
  { id: 'td-direct-investing', name: 'TD Direct Investing', logo: 'https://logo.clearbit.com/td.com', type: 'broker', region: 'north_america', description: 'Canada largest online brokerage platform.', founded: '1984', headquarters: 'Toronto, Canada', employees: '95,000+', communityTrust: 86, expertTrust: 88, regulated: true, regulators: ['IIROC', 'CIPF'] },
  { id: 'questrade', name: 'Questrade', logo: 'https://logo.clearbit.com/questrade.com', type: 'broker', region: 'north_america', description: 'Low-cost Canadian online brokerage.', founded: '1999', headquarters: 'Toronto, Canada', employees: '1,200+', communityTrust: 82, expertTrust: 80, regulated: true, regulators: ['IIROC', 'CIPF'] },
  { id: 'rbc', name: 'Royal Bank of Canada', logo: 'https://logo.clearbit.com/rbc.com', type: 'bank', region: 'north_america', description: 'Canada largest bank by market capitalization.', founded: '1869', headquarters: 'Toronto, Canada', aum: '$1.7T', employees: '97,000+', communityTrust: 88, expertTrust: 92, regulated: true, regulators: ['OSFI', 'IIROC'] },
  { id: 'td-bank', name: 'Toronto-Dominion Bank', logo: 'https://logo.clearbit.com/td.com', type: 'bank', region: 'north_america', description: 'Major Canadian multinational bank.', founded: '1955', headquarters: 'Toronto, Canada', aum: '$1.5T', employees: '95,000+', communityTrust: 86, expertTrust: 90, regulated: true, regulators: ['OSFI', 'IIROC'] },
  { id: 'bmo', name: 'Bank of Montreal', logo: 'https://logo.clearbit.com/bmo.com', type: 'bank', region: 'north_america', description: 'Fourth-largest bank in Canada.', founded: '1817', headquarters: 'Montreal, Canada', aum: '$950B', employees: '46,000+', communityTrust: 84, expertTrust: 88, regulated: true, regulators: ['OSFI'] },
  { id: 'scotiabank', name: 'Scotiabank', logo: 'https://logo.clearbit.com/scotiabank.com', type: 'bank', region: 'north_america', description: 'Canada third-largest bank with Latin America focus.', founded: '1832', headquarters: 'Toronto, Canada', aum: '$1.2T', employees: '90,000+', communityTrust: 82, expertTrust: 86, regulated: true, regulators: ['OSFI'] },
  { id: 'cibc', name: 'CIBC', logo: 'https://logo.clearbit.com/cibc.com', type: 'bank', region: 'north_america', description: 'Fifth-largest bank in Canada.', founded: '1961', headquarters: 'Toronto, Canada', aum: '$650B', employees: '48,000+', communityTrust: 80, expertTrust: 84, regulated: true, regulators: ['OSFI'] },
  { id: 'national-bank-canada', name: 'National Bank of Canada', logo: 'https://logo.clearbit.com/nbc.ca', type: 'bank', region: 'north_america', description: 'Sixth-largest bank in Canada.', founded: '1859', headquarters: 'Montreal, Canada', aum: '$400B', employees: '30,000+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['OSFI'] },
  { id: 'manulife', name: 'Manulife Financial', logo: 'https://logo.clearbit.com/manulife.com', type: 'asset_manager', region: 'north_america', description: 'Canadian multinational insurance and financial services.', founded: '1887', headquarters: 'Toronto, Canada', aum: '$1.3T', employees: '40,000+', communityTrust: 84, expertTrust: 88, regulated: true, regulators: ['OSFI'] },
  { id: 'brookfield', name: 'Brookfield Asset Management', logo: 'https://logo.clearbit.com/brookfield.com', type: 'asset_manager', region: 'north_america', description: 'Global alternative asset manager.', founded: '1899', headquarters: 'Toronto, Canada', aum: '$850B', employees: '200,000+', communityTrust: 82, expertTrust: 94, regulated: true, regulators: ['OSC'] },
  { id: 'power-corporation', name: 'Power Corporation of Canada', logo: 'https://logo.clearbit.com/powercorporation.com', type: 'asset_manager', region: 'north_america', description: 'Diversified management and holding company.', founded: '1925', headquarters: 'Montreal, Canada', aum: '$500B', employees: '45,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['OSC'] },

  // US Hedge Funds
  { id: 'bridgewater', name: 'Bridgewater Associates', logo: 'https://logo.clearbit.com/bridgewater.com', type: 'hedge_fund', region: 'north_america', description: 'World largest hedge fund known for macro investing.', founded: '1975', headquarters: 'Westport, CT', aum: '$150B', employees: '1,500+', communityTrust: 78, expertTrust: 96, regulated: true, regulators: ['SEC'] },
  { id: 'renaissance', name: 'Renaissance Technologies', logo: 'https://logo.clearbit.com/rentec.com', type: 'hedge_fund', region: 'north_america', description: 'Quantitative hedge fund with legendary Medallion Fund.', founded: '1982', headquarters: 'East Setauket, NY', aum: '$130B', employees: '300+', communityTrust: 82, expertTrust: 99, regulated: true, regulators: ['SEC'] },
  { id: 'citadel', name: 'Citadel LLC', logo: 'https://logo.clearbit.com/citadel.com', type: 'hedge_fund', region: 'north_america', description: 'Multi-strategy hedge fund and market maker.', founded: '1990', headquarters: 'Miami, FL', aum: '$62B', employees: '2,800+', communityTrust: 55, expertTrust: 92, regulated: true, regulators: ['SEC'] },
  { id: 'two-sigma', name: 'Two Sigma', logo: 'https://logo.clearbit.com/twosigma.com', type: 'hedge_fund', region: 'north_america', description: 'Technology-driven hedge fund using AI and machine learning.', founded: '2001', headquarters: 'New York, NY', aum: '$60B', employees: '2,000+', communityTrust: 75, expertTrust: 94, regulated: true, regulators: ['SEC'] },
  { id: 'de-shaw', name: 'D.E. Shaw & Co.', logo: 'https://logo.clearbit.com/deshaw.com', type: 'hedge_fund', region: 'north_america', description: 'Quantitative investment firm with systematic strategies.', founded: '1988', headquarters: 'New York, NY', aum: '$55B', employees: '2,500+', communityTrust: 72, expertTrust: 93, regulated: true, regulators: ['SEC'] },
  { id: 'millennium', name: 'Millennium Management', logo: 'https://logo.clearbit.com/mlp.com', type: 'hedge_fund', region: 'north_america', description: 'Multi-strategy hedge fund with global presence.', founded: '1989', headquarters: 'New York, NY', aum: '$58B', employees: '5,500+', communityTrust: 70, expertTrust: 91, regulated: true, regulators: ['SEC'] },
  { id: 'point72', name: 'Point72 Asset Management', logo: 'https://logo.clearbit.com/point72.com', type: 'hedge_fund', region: 'north_america', description: 'Discretionary hedge fund founded by Steve Cohen.', founded: '2014', headquarters: 'Stamford, CT', aum: '$32B', employees: '2,200+', communityTrust: 65, expertTrust: 88, regulated: true, regulators: ['SEC'] },
  { id: 'elliott', name: 'Elliott Investment Management', logo: 'https://logo.clearbit.com/elliottmgmt.com', type: 'hedge_fund', region: 'north_america', description: 'Activist hedge fund known for corporate campaigns.', founded: '1977', headquarters: 'West Palm Beach, FL', aum: '$55B', employees: '550+', communityTrust: 58, expertTrust: 90, regulated: true, regulators: ['SEC'] },
  { id: 'viking-global', name: 'Viking Global Investors', logo: 'https://logo.clearbit.com/vikingglobal.com', type: 'hedge_fund', region: 'north_america', description: 'Tiger cub hedge fund focused on long/short equity.', founded: '1999', headquarters: 'Greenwich, CT', aum: '$30B', employees: '200+', communityTrust: 74, expertTrust: 89, regulated: true, regulators: ['SEC'] },
  { id: 'lone-pine', name: 'Lone Pine Capital', logo: 'https://logo.clearbit.com/lonepinecapital.com', type: 'hedge_fund', region: 'north_america', description: 'Long/short equity hedge fund.', founded: '1997', headquarters: 'Greenwich, CT', aum: '$18B', employees: '100+', communityTrust: 76, expertTrust: 87, regulated: true, regulators: ['SEC'] },
  { id: 'tiger-global', name: 'Tiger Global Management', logo: 'https://logo.clearbit.com/tigerglobal.com', type: 'hedge_fund', region: 'north_america', description: 'Investment firm focused on global tech companies.', founded: '2001', headquarters: 'New York, NY', aum: '$35B', employees: '200+', communityTrust: 68, expertTrust: 86, regulated: true, regulators: ['SEC'] },
  { id: 'coatue', name: 'Coatue Management', logo: 'https://logo.clearbit.com/coatue.com', type: 'hedge_fund', region: 'north_america', description: 'Technology-focused investment manager.', founded: '1999', headquarters: 'New York, NY', aum: '$20B', employees: '150+', communityTrust: 72, expertTrust: 85, regulated: true, regulators: ['SEC'] },
  { id: 'pershing-square', name: 'Pershing Square Capital', logo: 'https://logo.clearbit.com/pershingsquareholdings.com', type: 'hedge_fund', region: 'north_america', description: 'Activist hedge fund run by Bill Ackman.', founded: '2004', headquarters: 'New York, NY', aum: '$16B', employees: '50+', communityTrust: 62, expertTrust: 84, regulated: true, regulators: ['SEC'] },
  { id: 'third-point', name: 'Third Point LLC', logo: 'https://logo.clearbit.com/thirdpoint.com', type: 'hedge_fund', region: 'north_america', description: 'Event-driven hedge fund by Daniel Loeb.', founded: '1995', headquarters: 'New York, NY', aum: '$14B', employees: '120+', communityTrust: 64, expertTrust: 86, regulated: true, regulators: ['SEC'] },
  { id: 'baupost', name: 'Baupost Group', logo: 'https://logo.clearbit.com/baupost.com', type: 'hedge_fund', region: 'north_america', description: 'Value-oriented investment partnership.', founded: '1982', headquarters: 'Boston, MA', aum: '$27B', employees: '200+', communityTrust: 78, expertTrust: 92, regulated: true, regulators: ['SEC'] },
  { id: 'appaloosa', name: 'Appaloosa Management', logo: 'https://logo.clearbit.com/appaloosamanagement.com', type: 'hedge_fund', region: 'north_america', description: 'Distressed debt hedge fund by David Tepper.', founded: '1993', headquarters: 'Short Hills, NJ', aum: '$13B', employees: '50+', communityTrust: 70, expertTrust: 88, regulated: true, regulators: ['SEC'] },
  { id: 'greenlight', name: 'Greenlight Capital', logo: 'https://logo.clearbit.com/greenlightcapital.com', type: 'hedge_fund', region: 'north_america', description: 'Value-oriented hedge fund by David Einhorn.', founded: '1996', headquarters: 'New York, NY', aum: '$3B', employees: '30+', communityTrust: 66, expertTrust: 82, regulated: true, regulators: ['SEC'] },
  { id: 'aqr', name: 'AQR Capital Management', logo: 'https://logo.clearbit.com/aqr.com', type: 'hedge_fund', region: 'north_america', description: 'Systematic quantitative investment manager.', founded: '1998', headquarters: 'Greenwich, CT', aum: '$98B', employees: '1,000+', communityTrust: 76, expertTrust: 93, regulated: true, regulators: ['SEC'] },
  { id: 'winton', name: 'Winton Group', logo: 'https://logo.clearbit.com/winton.com', type: 'hedge_fund', region: 'north_america', description: 'Quantitative investment management firm.', founded: '1997', headquarters: 'New York, NY', aum: '$8B', employees: '450+', communityTrust: 72, expertTrust: 85, regulated: true, regulators: ['SEC'] },
  { id: 'marshall-wace', name: 'Marshall Wace', logo: 'https://logo.clearbit.com/mwam.com', type: 'hedge_fund', region: 'north_america', description: 'Equity long/short hedge fund.', founded: '1997', headquarters: 'New York, NY', aum: '$62B', employees: '600+', communityTrust: 74, expertTrust: 88, regulated: true, regulators: ['SEC', 'FCA'] },

  // US Asset Managers
  { id: 'blackrock', name: 'BlackRock', logo: 'https://logo.clearbit.com/blackrock.com', type: 'asset_manager', region: 'north_america', description: 'World largest asset manager, creator of iShares ETFs.', founded: '1988', headquarters: 'New York, NY', aum: '$10T', employees: '21,000+', communityTrust: 85, expertTrust: 97, regulated: true, regulators: ['SEC', 'FCA'] },
  { id: 'vanguard', name: 'Vanguard', logo: 'https://logo.clearbit.com/vanguard.com', type: 'asset_manager', region: 'north_america', description: 'Pioneer of index investing with lowest-cost funds.', founded: '1975', headquarters: 'Malvern, PA', aum: '$8.6T', employees: '20,000+', communityTrust: 96, expertTrust: 98, regulated: true, regulators: ['SEC'] },
  { id: 'state-street', name: 'State Street Global Advisors', logo: 'https://logo.clearbit.com/ssga.com', type: 'asset_manager', region: 'north_america', description: 'Creator of first US ETF (SPY), major institutional manager.', founded: '1978', headquarters: 'Boston, MA', aum: '$4.1T', employees: '46,000+', communityTrust: 82, expertTrust: 93, regulated: true, regulators: ['SEC'] },
  { id: 'invesco', name: 'Invesco', logo: 'https://logo.clearbit.com/invesco.com', type: 'asset_manager', region: 'north_america', description: 'Global investment management company.', founded: '1935', headquarters: 'Atlanta, GA', aum: '$1.6T', employees: '8,500+', communityTrust: 78, expertTrust: 85, regulated: true, regulators: ['SEC', 'FCA'] },
  { id: 'pimco', name: 'PIMCO', logo: 'https://logo.clearbit.com/pimco.com', type: 'asset_manager', region: 'north_america', description: 'Leading fixed income investment manager.', founded: '1971', headquarters: 'Newport Beach, CA', aum: '$1.8T', employees: '3,200+', communityTrust: 84, expertTrust: 94, regulated: true, regulators: ['SEC'] },
  { id: 'capital-group', name: 'Capital Group', logo: 'https://logo.clearbit.com/capitalgroup.com', type: 'asset_manager', region: 'north_america', description: 'Manager of American Funds family.', founded: '1931', headquarters: 'Los Angeles, CA', aum: '$2.6T', employees: '8,500+', communityTrust: 86, expertTrust: 92, regulated: true, regulators: ['SEC'] },
  { id: 't-rowe-price', name: 'T. Rowe Price', logo: 'https://logo.clearbit.com/troweprice.com', type: 'asset_manager', region: 'north_america', description: 'Active investment management firm.', founded: '1937', headquarters: 'Baltimore, MD', aum: '$1.4T', employees: '7,500+', communityTrust: 84, expertTrust: 90, regulated: true, regulators: ['SEC'] },
  { id: 'wellington', name: 'Wellington Management', logo: 'https://logo.clearbit.com/wellington.com', type: 'asset_manager', region: 'north_america', description: 'Independent investment management firm.', founded: '1928', headquarters: 'Boston, MA', aum: '$1.2T', employees: '3,000+', communityTrust: 80, expertTrust: 91, regulated: true, regulators: ['SEC'] },
  { id: 'franklin-templeton', name: 'Franklin Templeton', logo: 'https://logo.clearbit.com/franklintempleton.com', type: 'asset_manager', region: 'north_america', description: 'Global investment management organization.', founded: '1947', headquarters: 'San Mateo, CA', aum: '$1.5T', employees: '9,500+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['SEC'] },
  { id: 'nuveen', name: 'Nuveen', logo: 'https://logo.clearbit.com/nuveen.com', type: 'asset_manager', region: 'north_america', description: 'Investment manager owned by TIAA.', founded: '1898', headquarters: 'Chicago, IL', aum: '$1.1T', employees: '2,000+', communityTrust: 76, expertTrust: 84, regulated: true, regulators: ['SEC'] },
  { id: 'northern-trust', name: 'Northern Trust', logo: 'https://logo.clearbit.com/northerntrust.com', type: 'asset_manager', region: 'north_america', description: 'Asset servicing and investment management.', founded: '1889', headquarters: 'Chicago, IL', aum: '$1.3T', employees: '23,000+', communityTrust: 82, expertTrust: 88, regulated: true, regulators: ['SEC', 'OCC'] },
  { id: 'pgim', name: 'PGIM', logo: 'https://logo.clearbit.com/pgim.com', type: 'asset_manager', region: 'north_america', description: 'Prudential investment management arm.', founded: '1875', headquarters: 'Newark, NJ', aum: '$1.5T', employees: '1,400+', communityTrust: 78, expertTrust: 87, regulated: true, regulators: ['SEC'] },
  { id: 'dimensional', name: 'Dimensional Fund Advisors', logo: 'https://logo.clearbit.com/dimensional.com', type: 'asset_manager', region: 'north_america', description: 'Factor-based investment manager.', founded: '1981', headquarters: 'Austin, TX', aum: '$650B', employees: '1,500+', communityTrust: 86, expertTrust: 92, regulated: true, regulators: ['SEC'] },
  { id: 'loomis-sayles', name: 'Loomis Sayles', logo: 'https://logo.clearbit.com/loomissayles.com', type: 'asset_manager', region: 'north_america', description: 'Fixed income investment manager.', founded: '1926', headquarters: 'Boston, MA', aum: '$320B', employees: '800+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['SEC'] },
  { id: 'mfs', name: 'MFS Investment Management', logo: 'https://logo.clearbit.com/mfs.com', type: 'asset_manager', region: 'north_america', description: 'Pioneer mutual fund company.', founded: '1924', headquarters: 'Boston, MA', aum: '$600B', employees: '2,000+', communityTrust: 82, expertTrust: 87, regulated: true, regulators: ['SEC'] },

  // US Banks
  { id: 'jpmorgan', name: 'JPMorgan Chase', logo: 'https://logo.clearbit.com/jpmorganchase.com', type: 'bank', region: 'north_america', description: 'Largest US bank with full investment banking services.', founded: '2000', headquarters: 'New York, NY', aum: '$3.2T', employees: '313,000+', communityTrust: 72, expertTrust: 95, regulated: true, regulators: ['OCC', 'Fed', 'SEC'] },
  { id: 'goldman-sachs', name: 'Goldman Sachs', logo: 'https://logo.clearbit.com/goldmansachs.com', type: 'bank', region: 'north_america', description: 'Premier investment bank and wealth management firm.', founded: '1869', headquarters: 'New York, NY', aum: '$2.8T', employees: '45,000+', communityTrust: 65, expertTrust: 96, regulated: true, regulators: ['Fed', 'SEC', 'FCA'] },
  { id: 'morgan-stanley', name: 'Morgan Stanley', logo: 'https://logo.clearbit.com/morganstanley.com', type: 'bank', region: 'north_america', description: 'Global financial services firm with wealth management focus.', founded: '1935', headquarters: 'New York, NY', aum: '$1.5T', employees: '82,000+', communityTrust: 74, expertTrust: 93, regulated: true, regulators: ['Fed', 'SEC'] },
  { id: 'bank-of-america', name: 'Bank of America', logo: 'https://logo.clearbit.com/bankofamerica.com', type: 'bank', region: 'north_america', description: 'Second-largest bank in the United States.', founded: '1998', headquarters: 'Charlotte, NC', aum: '$1.1T', employees: '216,000+', communityTrust: 70, expertTrust: 88, regulated: true, regulators: ['OCC', 'Fed'] },
  { id: 'citigroup', name: 'Citigroup', logo: 'https://logo.clearbit.com/citigroup.com', type: 'bank', region: 'north_america', description: 'Global banking and financial services.', founded: '1998', headquarters: 'New York, NY', aum: '$750B', employees: '240,000+', communityTrust: 68, expertTrust: 86, regulated: true, regulators: ['OCC', 'Fed'] },
  { id: 'wells-fargo', name: 'Wells Fargo', logo: 'https://logo.clearbit.com/wellsfargo.com', type: 'bank', region: 'north_america', description: 'Diversified financial services company.', founded: '1852', headquarters: 'San Francisco, CA', aum: '$600B', employees: '227,000+', communityTrust: 58, expertTrust: 78, regulated: true, regulators: ['OCC', 'Fed'] },
  { id: 'us-bank', name: 'U.S. Bancorp', logo: 'https://logo.clearbit.com/usbank.com', type: 'bank', region: 'north_america', description: 'Fifth-largest bank in the United States.', founded: '1863', headquarters: 'Minneapolis, MN', aum: '$400B', employees: '77,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['OCC', 'Fed'] },
  { id: 'pnc', name: 'PNC Financial Services', logo: 'https://logo.clearbit.com/pnc.com', type: 'bank', region: 'north_america', description: 'Regional bank with nationwide presence.', founded: '1845', headquarters: 'Pittsburgh, PA', aum: '$320B', employees: '56,000+', communityTrust: 78, expertTrust: 80, regulated: true, regulators: ['Fed', 'OCC'] },
  { id: 'truist', name: 'Truist Financial', logo: 'https://logo.clearbit.com/truist.com', type: 'bank', region: 'north_america', description: 'Regional bank formed by BB&T and SunTrust merger.', founded: '2019', headquarters: 'Charlotte, NC', aum: '$280B', employees: '50,000+', communityTrust: 74, expertTrust: 78, regulated: true, regulators: ['Fed', 'OCC'] },
  // ===== EUROPE =====
  // UK Banks & Brokers
  { id: 'hsbc', name: 'HSBC Holdings', logo: 'https://logo.clearbit.com/hsbc.com', type: 'bank', region: 'europe', description: 'UK largest bank with global presence.', founded: '1865', headquarters: 'London, UK', aum: '$3.0T', employees: '219,000+', communityTrust: 78, expertTrust: 92, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'barclays', name: 'Barclays', logo: 'https://logo.clearbit.com/barclays.com', type: 'bank', region: 'europe', description: 'British universal bank with investment banking.', founded: '1690', headquarters: 'London, UK', aum: '$1.5T', employees: '92,000+', communityTrust: 72, expertTrust: 88, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'lloyds', name: 'Lloyds Banking Group', logo: 'https://logo.clearbit.com/lloydsbank.com', type: 'bank', region: 'europe', description: 'UK largest retail bank.', founded: '1765', headquarters: 'London, UK', aum: '$900B', employees: '63,000+', communityTrust: 76, expertTrust: 84, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'natwest', name: 'NatWest Group', logo: 'https://logo.clearbit.com/natwest.com', type: 'bank', region: 'europe', description: 'Major UK banking group.', founded: '1968', headquarters: 'Edinburgh, UK', aum: '$750B', employees: '64,000+', communityTrust: 74, expertTrust: 82, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'standard-chartered', name: 'Standard Chartered', logo: 'https://logo.clearbit.com/sc.com', type: 'bank', region: 'europe', description: 'International bank focused on emerging markets.', founded: '1969', headquarters: 'London, UK', aum: '$800B', employees: '85,000+', communityTrust: 70, expertTrust: 86, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'schroders', name: 'Schroders', logo: 'https://logo.clearbit.com/schroders.com', type: 'asset_manager', region: 'europe', description: 'British multinational asset management company.', founded: '1804', headquarters: 'London, UK', aum: '$990B', employees: '6,200+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['FCA'] },
  { id: 'abrdn', name: 'abrdn', logo: 'https://logo.clearbit.com/abrdn.com', type: 'asset_manager', region: 'europe', description: 'Global investment company.', founded: '1825', headquarters: 'Edinburgh, UK', aum: '$580B', employees: '5,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['FCA'] },
  { id: 'legal-general', name: 'Legal & General', logo: 'https://logo.clearbit.com/legalandgeneral.com', type: 'asset_manager', region: 'europe', description: 'UK investment management and insurance.', founded: '1836', headquarters: 'London, UK', aum: '$1.5T', employees: '11,000+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['FCA', 'PRA'] },
  { id: 'man-group', name: 'Man Group', logo: 'https://logo.clearbit.com/man.com', type: 'hedge_fund', region: 'europe', description: 'Worlds largest publicly traded hedge fund.', founded: '1783', headquarters: 'London, UK', aum: '$150B', employees: '1,600+', communityTrust: 74, expertTrust: 88, regulated: true, regulators: ['FCA'] },
  { id: 'hargreaves-lansdown', name: 'Hargreaves Lansdown', logo: 'https://logo.clearbit.com/hl.co.uk', type: 'broker', region: 'europe', description: 'UK largest retail investment platform.', founded: '1981', headquarters: 'Bristol, UK', employees: '2,200+', communityTrust: 86, expertTrust: 84, regulated: true, regulators: ['FCA'] },
  { id: 'ig-group', name: 'IG Group', logo: 'https://logo.clearbit.com/ig.com', type: 'broker', region: 'europe', description: 'UK spread betting and CFD provider.', founded: '1974', headquarters: 'London, UK', employees: '2,500+', communityTrust: 78, expertTrust: 80, regulated: true, regulators: ['FCA'] },
  { id: 'cmc-markets', name: 'CMC Markets', logo: 'https://logo.clearbit.com/cmcmarkets.com', type: 'broker', region: 'europe', description: 'Online trading and CFD provider.', founded: '1989', headquarters: 'London, UK', employees: '900+', communityTrust: 76, expertTrust: 78, regulated: true, regulators: ['FCA'] },
  

  // Germany
  { id: 'deutsche-bank', name: 'Deutsche Bank', logo: 'https://logo.clearbit.com/db.com', type: 'bank', region: 'europe', description: 'Germany largest bank.', founded: '1870', headquarters: 'Frankfurt, Germany', aum: '$1.4T', employees: '87,000+', communityTrust: 68, expertTrust: 85, regulated: true, regulators: ['BaFin', 'ECB'] },
  { id: 'commerzbank', name: 'Commerzbank', logo: 'https://logo.clearbit.com/commerzbank.com', type: 'bank', region: 'europe', description: 'Major German commercial bank.', founded: '1870', headquarters: 'Frankfurt, Germany', aum: '$520B', employees: '37,000+', communityTrust: 70, expertTrust: 78, regulated: true, regulators: ['BaFin', 'ECB'] },
  { id: 'dws', name: 'DWS Group', logo: 'https://logo.clearbit.com/dws.com', type: 'asset_manager', region: 'europe', description: 'German asset management company.', founded: '1956', headquarters: 'Frankfurt, Germany', aum: '$900B', employees: '3,600+', communityTrust: 76, expertTrust: 84, regulated: true, regulators: ['BaFin'] },
  { id: 'allianz-gi', name: 'Allianz Global Investors', logo: 'https://logo.clearbit.com/allianzgi.com', type: 'asset_manager', region: 'europe', description: 'Active investment manager.', founded: '1890', headquarters: 'Munich, Germany', aum: '$700B', employees: '2,400+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['BaFin'] },
  
  { id: 'trade-republic', name: 'Trade Republic', logo: 'https://logo.clearbit.com/traderepublic.com', type: 'broker', region: 'europe', description: 'German commission-free broker.', founded: '2015', headquarters: 'Berlin, Germany', employees: '800+', communityTrust: 74, expertTrust: 70, regulated: true, regulators: ['BaFin'] },

  // France
  { id: 'bnp-paribas', name: 'BNP Paribas', logo: 'https://logo.clearbit.com/bnpparibas.com', type: 'bank', region: 'europe', description: 'France largest bank.', founded: '2000', headquarters: 'Paris, France', aum: '$2.8T', employees: '193,000+', communityTrust: 76, expertTrust: 90, regulated: true, regulators: ['AMF', 'ECB'] },
  { id: 'societe-generale', name: 'Société Générale', logo: 'https://logo.clearbit.com/societegenerale.com', type: 'bank', region: 'europe', description: 'Major French multinational bank.', founded: '1864', headquarters: 'Paris, France', aum: '$1.5T', employees: '117,000+', communityTrust: 72, expertTrust: 86, regulated: true, regulators: ['AMF', 'ECB'] },
  { id: 'credit-agricole', name: 'Crédit Agricole', logo: 'https://logo.clearbit.com/credit-agricole.com', type: 'bank', region: 'europe', description: 'French cooperative banking group.', founded: '1894', headquarters: 'Paris, France', aum: '$2.2T', employees: '142,000+', communityTrust: 78, expertTrust: 88, regulated: true, regulators: ['AMF', 'ECB'] },
  { id: 'amundi', name: 'Amundi', logo: 'https://logo.clearbit.com/amundi.com', type: 'asset_manager', region: 'europe', description: 'Europe largest asset manager.', founded: '2010', headquarters: 'Paris, France', aum: '$2.0T', employees: '5,400+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['AMF'] },
  { id: 'axa-im', name: 'AXA Investment Managers', logo: 'https://logo.clearbit.com/axa-im.com', type: 'asset_manager', region: 'europe', description: 'Global asset manager.', founded: '1997', headquarters: 'Paris, France', aum: '$860B', employees: '2,700+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['AMF'] },
  

  // Switzerland
  { id: 'ubs', name: 'UBS', logo: 'https://logo.clearbit.com/ubs.com', type: 'bank', region: 'europe', description: 'Swiss multinational investment bank.', founded: '1862', headquarters: 'Zurich, Switzerland', aum: '$4.0T', employees: '115,000+', communityTrust: 80, expertTrust: 94, regulated: true, regulators: ['FINMA'] },
  { id: 'credit-suisse', name: 'Credit Suisse', logo: 'https://logo.clearbit.com/credit-suisse.com', type: 'bank', region: 'europe', description: 'Swiss global investment bank (now part of UBS).', founded: '1856', headquarters: 'Zurich, Switzerland', aum: '$1.5T', employees: '50,000+', communityTrust: 62, expertTrust: 78, regulated: true, regulators: ['FINMA'] },
  { id: 'julius-baer', name: 'Julius Baer', logo: 'https://logo.clearbit.com/juliusbaer.com', type: 'wealth_manager', region: 'europe', description: 'Swiss private banking group.', founded: '1890', headquarters: 'Zurich, Switzerland', aum: '$480B', employees: '7,000+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['FINMA'] },
  { id: 'pictet', name: 'Pictet Group', logo: 'https://logo.clearbit.com/pictet.com', type: 'wealth_manager', region: 'europe', description: 'Swiss private bank and asset manager.', founded: '1805', headquarters: 'Geneva, Switzerland', aum: '$700B', employees: '5,500+', communityTrust: 84, expertTrust: 92, regulated: true, regulators: ['FINMA'] },
  { id: 'lombard-odier', name: 'Lombard Odier', logo: 'https://logo.clearbit.com/lombardodier.com', type: 'wealth_manager', region: 'europe', description: 'Swiss private bank.', founded: '1796', headquarters: 'Geneva, Switzerland', aum: '$300B', employees: '2,600+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['FINMA'] },
  
  { id: 'swissquote', name: 'Swissquote', logo: 'https://logo.clearbit.com/swissquote.com', type: 'broker', region: 'europe', description: 'Swiss online bank and broker.', founded: '1996', headquarters: 'Gland, Switzerland', employees: '1,100+', communityTrust: 80, expertTrust: 82, regulated: true, regulators: ['FINMA'] },

  // Netherlands
  { id: 'ing', name: 'ING Group', logo: 'https://logo.clearbit.com/ing.com', type: 'bank', region: 'europe', description: 'Dutch multinational banking corporation.', founded: '1991', headquarters: 'Amsterdam, Netherlands', aum: '$950B', employees: '60,000+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['DNB', 'ECB'] },
  { id: 'abn-amro', name: 'ABN AMRO', logo: 'https://logo.clearbit.com/abnamro.com', type: 'bank', region: 'europe', description: 'Dutch state-owned bank.', founded: '1991', headquarters: 'Amsterdam, Netherlands', aum: '$400B', employees: '20,000+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['DNB', 'ECB'] },
  { id: 'robeco', name: 'Robeco', logo: 'https://logo.clearbit.com/robeco.com', type: 'asset_manager', region: 'europe', description: 'Dutch asset management firm.', founded: '1929', headquarters: 'Rotterdam, Netherlands', aum: '$190B', employees: '1,100+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['AFM'] },
  { id: 'degiro', name: 'DEGIRO', logo: 'https://logo.clearbit.com/degiro.com', type: 'broker', region: 'europe', description: 'Low-cost European online broker.', founded: '2008', headquarters: 'Amsterdam, Netherlands', employees: '600+', communityTrust: 82, expertTrust: 78, regulated: true, regulators: ['AFM'] },
  

  // Spain & Italy
  { id: 'santander', name: 'Banco Santander', logo: 'https://logo.clearbit.com/santander.com', type: 'bank', region: 'europe', description: 'Spain largest bank.', founded: '1857', headquarters: 'Santander, Spain', aum: '$1.8T', employees: '212,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['CNMV', 'ECB'] },
  { id: 'bbva', name: 'BBVA', logo: 'https://logo.clearbit.com/bbva.com', type: 'bank', region: 'europe', description: 'Spanish multinational banking group.', founded: '1857', headquarters: 'Bilbao, Spain', aum: '$780B', employees: '115,000+', communityTrust: 74, expertTrust: 84, regulated: true, regulators: ['CNMV', 'ECB'] },
  { id: 'caixabank', name: 'CaixaBank', logo: 'https://logo.clearbit.com/caixabank.com', type: 'bank', region: 'europe', description: 'Spanish retail bank.', founded: '2011', headquarters: 'Barcelona, Spain', aum: '$500B', employees: '45,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['CNMV', 'ECB'] },
  { id: 'intesa', name: 'Intesa Sanpaolo', logo: 'https://logo.clearbit.com/intesasanpaolo.com', type: 'bank', region: 'europe', description: 'Italy largest bank.', founded: '2007', headquarters: 'Turin, Italy', aum: '$900B', employees: '96,000+', communityTrust: 74, expertTrust: 86, regulated: true, regulators: ['CONSOB', 'ECB'] },
  { id: 'unicredit', name: 'UniCredit', logo: 'https://logo.clearbit.com/unicredit.eu', type: 'bank', region: 'europe', description: 'Italian banking group.', founded: '1998', headquarters: 'Milan, Italy', aum: '$950B', employees: '76,000+', communityTrust: 72, expertTrust: 84, regulated: true, regulators: ['CONSOB', 'ECB'] },

  // Nordic Countries
  { id: 'nordea', name: 'Nordea', logo: 'https://logo.clearbit.com/nordea.com', type: 'bank', region: 'europe', description: 'Largest Nordic bank.', founded: '2001', headquarters: 'Helsinki, Finland', aum: '$400B', employees: '28,000+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['FIN-FSA', 'ECB'] },
  { id: 'danske-bank', name: 'Danske Bank', logo: 'https://logo.clearbit.com/danskebank.com', type: 'bank', region: 'europe', description: 'Denmark largest bank.', founded: '1871', headquarters: 'Copenhagen, Denmark', aum: '$350B', employees: '21,000+', communityTrust: 72, expertTrust: 82, regulated: true, regulators: ['Danish FSA'] },
  { id: 'seb', name: 'SEB', logo: 'https://logo.clearbit.com/seb.se', type: 'bank', region: 'europe', description: 'Swedish universal bank.', founded: '1856', headquarters: 'Stockholm, Sweden', aum: '$350B', employees: '17,000+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['FI Sweden'] },
  { id: 'swedbank', name: 'Swedbank', logo: 'https://logo.clearbit.com/swedbank.com', type: 'bank', region: 'europe', description: 'Swedish retail bank.', founded: '1820', headquarters: 'Stockholm, Sweden', aum: '$250B', employees: '14,000+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['FI Sweden'] },
  { id: 'handelsbanken', name: 'Handelsbanken', logo: 'https://logo.clearbit.com/handelsbanken.com', type: 'bank', region: 'europe', description: 'Swedish universal bank.', founded: '1871', headquarters: 'Stockholm, Sweden', aum: '$300B', employees: '12,000+', communityTrust: 82, expertTrust: 88, regulated: true, regulators: ['FI Sweden'] },
  { id: 'dnb', name: 'DNB', logo: 'https://logo.clearbit.com/dnb.no', type: 'bank', region: 'europe', description: 'Norway largest bank.', founded: '2003', headquarters: 'Oslo, Norway', aum: '$350B', employees: '9,000+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['FSA Norway'] },
  { id: 'saxo-bank', name: 'Saxo Bank', logo: 'https://logo.clearbit.com/saxo.com', type: 'broker', region: 'europe', description: 'Danish investment bank and broker.', founded: '1992', headquarters: 'Copenhagen, Denmark', employees: '2,500+', communityTrust: 80, expertTrust: 84, regulated: true, regulators: ['Danish FSA'] },
  { id: 'nordnet', name: 'Nordnet', logo: 'https://logo.clearbit.com/nordnet.se', type: 'broker', region: 'europe', description: 'Nordic digital platform for savings and investments.', founded: '1996', headquarters: 'Stockholm, Sweden', employees: '800+', communityTrust: 82, expertTrust: 80, regulated: true, regulators: ['FI Sweden'] },
  { id: 'avanza', name: 'Avanza', logo: 'https://logo.clearbit.com/avanza.se', type: 'broker', region: 'europe', description: 'Swedish online broker.', founded: '1999', headquarters: 'Stockholm, Sweden', employees: '700+', communityTrust: 84, expertTrust: 82, regulated: true, regulators: ['FI Sweden'] },
  

  // ===== ASIA PACIFIC =====
  // Japan
  { id: 'nomura', name: 'Nomura Holdings', logo: 'https://logo.clearbit.com/nomura.com', type: 'bank', region: 'asia_pacific', description: 'Japan largest investment bank.', founded: '1925', headquarters: 'Tokyo, Japan', aum: '$550B', employees: '27,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['FSA Japan'] },
  { id: 'daiwa', name: 'Daiwa Securities', logo: 'https://logo.clearbit.com/daiwa.jp', type: 'broker', region: 'asia_pacific', description: 'Major Japanese securities firm.', founded: '1902', headquarters: 'Tokyo, Japan', employees: '14,000+', communityTrust: 74, expertTrust: 84, regulated: true, regulators: ['FSA Japan'] },
  { id: 'nikko-am', name: 'Nikko Asset Management', logo: 'https://logo.clearbit.com/nikkoam.com', type: 'asset_manager', region: 'asia_pacific', description: 'Japanese asset management company.', founded: '1959', headquarters: 'Tokyo, Japan', aum: '$230B', employees: '1,300+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['FSA Japan'] },
  { id: 'mizuho', name: 'Mizuho Financial Group', logo: 'https://logo.clearbit.com/mizuhogroup.com', type: 'bank', region: 'asia_pacific', description: 'One of Japan big three banks.', founded: '2000', headquarters: 'Tokyo, Japan', aum: '$1.8T', employees: '55,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['FSA Japan'] },
  { id: 'mufg', name: 'MUFG', logo: 'https://logo.clearbit.com/mufg.jp', type: 'bank', region: 'asia_pacific', description: 'Japan largest bank.', founded: '2005', headquarters: 'Tokyo, Japan', aum: '$2.8T', employees: '150,000+', communityTrust: 78, expertTrust: 90, regulated: true, regulators: ['FSA Japan'] },
  { id: 'smfg', name: 'Sumitomo Mitsui', logo: 'https://logo.clearbit.com/smfg.co.jp', type: 'bank', region: 'asia_pacific', description: 'Major Japanese banking group.', founded: '2002', headquarters: 'Tokyo, Japan', aum: '$2.0T', employees: '86,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['FSA Japan'] },
  
  { id: 'gpif', name: 'GPIF', logo: 'https://logo.clearbit.com/gpif.go.jp', type: 'pension_fund', region: 'asia_pacific', description: 'World largest pension fund.', founded: '2006', headquarters: 'Tokyo, Japan', aum: '$1.7T', employees: '200+', communityTrust: 84, expertTrust: 92, regulated: true, regulators: ['MHLW'] },
  { id: 'rakuten-sec', name: 'Rakuten Securities', logo: 'https://logo.clearbit.com/rakuten-sec.co.jp', type: 'broker', region: 'asia_pacific', description: 'Japanese online broker.', founded: '1999', headquarters: 'Tokyo, Japan', employees: '1,200+', communityTrust: 78, expertTrust: 76, regulated: true, regulators: ['FSA Japan'] },
  { id: 'sbi-sec', name: 'SBI Securities', logo: 'https://logo.clearbit.com/sbisec.co.jp', type: 'broker', region: 'asia_pacific', description: 'Japan largest online broker.', founded: '1999', headquarters: 'Tokyo, Japan', employees: '1,500+', communityTrust: 80, expertTrust: 78, regulated: true, regulators: ['FSA Japan'] },

  // Hong Kong
  
  { id: 'hk-mpi', name: 'Hong Kong Monetary Authority', logo: 'https://logo.clearbit.com/hkma.gov.hk', type: 'asset_manager', region: 'asia_pacific', description: 'Hong Kong sovereign wealth manager.', founded: '1993', headquarters: 'Hong Kong', aum: '$500B', employees: '900+', communityTrust: 82, expertTrust: 92, regulated: true, regulators: ['HKMA'] },
  { id: 'boc-hk', name: 'Bank of China (Hong Kong)', logo: 'https://logo.clearbit.com/bochk.com', type: 'bank', region: 'asia_pacific', description: 'Second largest banking group in Hong Kong.', founded: '2001', headquarters: 'Hong Kong', aum: '$400B', employees: '14,000+', communityTrust: 76, expertTrust: 86, regulated: true, regulators: ['HKMA'] },
  { id: 'hang-seng', name: 'Hang Seng Bank', logo: 'https://logo.clearbit.com/hangseng.com', type: 'bank', region: 'asia_pacific', description: 'Major Hong Kong bank.', founded: '1933', headquarters: 'Hong Kong', aum: '$200B', employees: '8,000+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['HKMA'] },
  { id: 'hsbc-hk', name: 'HSBC Hong Kong', logo: 'https://logo.clearbit.com/hsbc.com.hk', type: 'bank', region: 'asia_pacific', description: 'Largest bank in Hong Kong.', founded: '1865', headquarters: 'Hong Kong', aum: '$800B', employees: '29,000+', communityTrust: 78, expertTrust: 88, regulated: true, regulators: ['HKMA'] },
  { id: 'value-partners', name: 'Value Partners', logo: 'https://logo.clearbit.com/valuepartners-group.com', type: 'asset_manager', region: 'asia_pacific', description: 'Hong Kong asset manager.', founded: '1993', headquarters: 'Hong Kong', aum: '$8B', employees: '200+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['SFC'] },

  // Singapore
  { id: 'dbs', name: 'DBS Bank', logo: 'https://logo.clearbit.com/dbs.com', type: 'bank', region: 'asia_pacific', description: 'Southeast Asia largest bank.', founded: '1968', headquarters: 'Singapore', aum: '$450B', employees: '36,000+', communityTrust: 84, expertTrust: 92, regulated: true, regulators: ['MAS'] },
  { id: 'ocbc', name: 'OCBC Bank', logo: 'https://logo.clearbit.com/ocbc.com', type: 'bank', region: 'asia_pacific', description: 'Second largest bank in Singapore.', founded: '1932', headquarters: 'Singapore', aum: '$350B', employees: '32,000+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['MAS'] },
  { id: 'uob', name: 'United Overseas Bank', logo: 'https://logo.clearbit.com/uobgroup.com', type: 'bank', region: 'asia_pacific', description: 'Third largest bank in Singapore.', founded: '1935', headquarters: 'Singapore', aum: '$320B', employees: '24,000+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['MAS'] },
  { id: 'gic', name: 'GIC', logo: 'https://logo.clearbit.com/gic.com.sg', type: 'pension_fund', region: 'asia_pacific', description: 'Singapore sovereign wealth fund.', founded: '1981', headquarters: 'Singapore', aum: '$770B', employees: '2,000+', communityTrust: 84, expertTrust: 94, regulated: true, regulators: ['MAS'] },
  { id: 'temasek', name: 'Temasek Holdings', logo: 'https://logo.clearbit.com/temasek.com.sg', type: 'pension_fund', region: 'asia_pacific', description: 'Singapore state investment company.', founded: '1974', headquarters: 'Singapore', aum: '$290B', employees: '800+', communityTrust: 82, expertTrust: 92, regulated: true, regulators: ['MAS'] },
  
  { id: 'tiger-brokers', name: 'Tiger Brokers', logo: 'https://logo.clearbit.com/tigerbrokers.com', type: 'broker', region: 'asia_pacific', description: 'Asian online brokerage platform.', founded: '2014', headquarters: 'Singapore', employees: '1,500+', communityTrust: 74, expertTrust: 72, regulated: true, regulators: ['MAS'] },

  // Australia
  { id: 'cba', name: 'Commonwealth Bank', logo: 'https://logo.clearbit.com/commbank.com.au', type: 'bank', region: 'asia_pacific', description: 'Australia largest bank.', founded: '1911', headquarters: 'Sydney, Australia', aum: '$900B', employees: '53,000+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['APRA', 'ASIC'] },
  { id: 'westpac', name: 'Westpac', logo: 'https://logo.clearbit.com/westpac.com.au', type: 'bank', region: 'asia_pacific', description: 'Australia second largest bank.', founded: '1817', headquarters: 'Sydney, Australia', aum: '$750B', employees: '39,000+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['APRA', 'ASIC'] },
  { id: 'nab', name: 'National Australia Bank', logo: 'https://logo.clearbit.com/nab.com.au', type: 'bank', region: 'asia_pacific', description: 'Major Australian bank.', founded: '1982', headquarters: 'Melbourne, Australia', aum: '$700B', employees: '36,000+', communityTrust: 76, expertTrust: 84, regulated: true, regulators: ['APRA', 'ASIC'] },
  { id: 'anz', name: 'ANZ Bank', logo: 'https://logo.clearbit.com/anz.com', type: 'bank', region: 'asia_pacific', description: 'Australian and New Zealand bank.', founded: '1835', headquarters: 'Melbourne, Australia', aum: '$650B', employees: '40,000+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['APRA', 'ASIC'] },
  { id: 'macquarie', name: 'Macquarie Group', logo: 'https://logo.clearbit.com/macquarie.com', type: 'bank', region: 'asia_pacific', description: 'Australian investment bank.', founded: '1969', headquarters: 'Sydney, Australia', aum: '$580B', employees: '20,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['APRA', 'ASIC'] },
  
  { id: 'australian-super', name: 'AustralianSuper', logo: 'https://logo.clearbit.com/australiansuper.com', type: 'pension_fund', region: 'asia_pacific', description: 'Australia largest superannuation fund.', founded: '2006', headquarters: 'Melbourne, Australia', aum: '$270B', employees: '1,400+', communityTrust: 84, expertTrust: 88, regulated: true, regulators: ['APRA'] },
  { id: 'future-fund', name: 'Future Fund', logo: 'https://logo.clearbit.com/futurefund.gov.au', type: 'pension_fund', region: 'asia_pacific', description: 'Australia sovereign wealth fund.', founded: '2006', headquarters: 'Melbourne, Australia', aum: '$200B', employees: '200+', communityTrust: 86, expertTrust: 92, regulated: true, regulators: ['APRA'] },
  { id: 'commsec', name: 'CommSec', logo: 'https://logo.clearbit.com/commsec.com.au', type: 'broker', region: 'asia_pacific', description: 'Australia largest online broker.', founded: '1995', headquarters: 'Sydney, Australia', employees: '1,000+', communityTrust: 82, expertTrust: 80, regulated: true, regulators: ['ASIC'] },
  { id: 'stake', name: 'Stake', logo: 'https://logo.clearbit.com/stake.com.au', type: 'broker', region: 'asia_pacific', description: 'Australian commission-free broker.', founded: '2017', headquarters: 'Sydney, Australia', employees: '150+', communityTrust: 74, expertTrust: 70, regulated: true, regulators: ['ASIC'] },

  // South Korea
  { id: 'keb-hana', name: 'KEB Hana Bank', logo: 'https://logo.clearbit.com/kebhana.com', type: 'bank', region: 'asia_pacific', description: 'South Korea major bank.', founded: '2015', headquarters: 'Seoul, South Korea', aum: '$400B', employees: '21,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['FSS'] },
  { id: 'kb', name: 'KB Financial Group', logo: 'https://logo.clearbit.com/kbfg.com', type: 'bank', region: 'asia_pacific', description: 'South Korea largest financial group.', founded: '2008', headquarters: 'Seoul, South Korea', aum: '$550B', employees: '40,000+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['FSS'] },
  { id: 'shinhan', name: 'Shinhan Financial Group', logo: 'https://logo.clearbit.com/shinhan.com', type: 'bank', region: 'asia_pacific', description: 'South Korea financial group.', founded: '2001', headquarters: 'Seoul, South Korea', aum: '$450B', employees: '23,000+', communityTrust: 78, expertTrust: 86, regulated: true, regulators: ['FSS'] },
  { id: 'samsung-securities', name: 'Samsung Securities', logo: 'https://logo.clearbit.com/samsungsecurities.com', type: 'broker', region: 'asia_pacific', description: 'Leading Korean brokerage firm.', founded: '1982', headquarters: 'Seoul, South Korea', employees: '3,000+', communityTrust: 80, expertTrust: 84, regulated: true, regulators: ['FSS'] },
  { id: 'kic', name: 'Korea Investment Corporation', logo: 'https://logo.clearbit.com/kic.kr', type: 'pension_fund', region: 'asia_pacific', description: 'South Korea sovereign wealth fund.', founded: '2005', headquarters: 'Seoul, South Korea', aum: '$240B', employees: '350+', communityTrust: 82, expertTrust: 90, regulated: true, regulators: ['FSS'] },
  { id: 'nps', name: 'National Pension Service', logo: 'https://logo.clearbit.com/nps.or.kr', type: 'pension_fund', region: 'asia_pacific', description: 'Third largest pension fund globally.', founded: '1988', headquarters: 'Seoul, South Korea', aum: '$850B', employees: '1,500+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['MOHW'] },
  
  { id: 'mirae-asset', name: 'Mirae Asset', logo: 'https://logo.clearbit.com/miraeasset.com', type: 'asset_manager', region: 'asia_pacific', description: 'South Korean asset manager.', founded: '1997', headquarters: 'Seoul, South Korea', aum: '$580B', employees: '15,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['FSS'] },

  // ===== MIDDLE EAST & AFRICA =====
  // UAE
  { id: 'emirates-nbd', name: 'Emirates NBD', logo: 'https://logo.clearbit.com/emiratesnbd.com', type: 'bank', region: 'middle_east_africa', description: 'UAE largest bank.', founded: '2007', headquarters: 'Dubai, UAE', aum: '$200B', employees: '25,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['CBUAE'] },
  { id: 'fab', name: 'First Abu Dhabi Bank', logo: 'https://logo.clearbit.com/bankfab.com', type: 'bank', region: 'middle_east_africa', description: 'UAE largest bank by assets.', founded: '2017', headquarters: 'Abu Dhabi, UAE', aum: '$300B', employees: '12,000+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['CBUAE'] },
  { id: 'adia', name: 'Abu Dhabi Investment Authority', logo: 'https://logo.clearbit.com/adia.ae', type: 'pension_fund', region: 'middle_east_africa', description: 'One of world largest sovereign wealth funds.', founded: '1976', headquarters: 'Abu Dhabi, UAE', aum: '$850B', employees: '1,800+', communityTrust: 78, expertTrust: 94, regulated: true, regulators: ['CBUAE'] },
  { id: 'mubadala', name: 'Mubadala', logo: 'https://logo.clearbit.com/mubadala.com', type: 'pension_fund', region: 'middle_east_africa', description: 'Abu Dhabi sovereign wealth fund.', founded: '2002', headquarters: 'Abu Dhabi, UAE', aum: '$280B', employees: '1,200+', communityTrust: 80, expertTrust: 90, regulated: true, regulators: ['CBUAE'] },
  
  

  // Saudi Arabia
  { id: 'snb', name: 'Saudi National Bank', logo: 'https://logo.clearbit.com/snb.com', type: 'bank', region: 'middle_east_africa', description: 'Saudi Arabia largest bank.', founded: '2021', headquarters: 'Riyadh, Saudi Arabia', aum: '$250B', employees: '15,000+', communityTrust: 76, expertTrust: 86, regulated: true, regulators: ['SAMA'] },
  { id: 'al-rajhi', name: 'Al Rajhi Bank', logo: 'https://logo.clearbit.com/alrajhibank.com.sa', type: 'bank', region: 'middle_east_africa', description: 'Largest Islamic bank in the world.', founded: '1957', headquarters: 'Riyadh, Saudi Arabia', aum: '$180B', employees: '12,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['SAMA'] },
  { id: 'pif', name: 'Public Investment Fund', logo: 'https://logo.clearbit.com/pif.gov.sa', type: 'pension_fund', region: 'middle_east_africa', description: 'Saudi Arabia sovereign wealth fund.', founded: '1971', headquarters: 'Riyadh, Saudi Arabia', aum: '$930B', employees: '2,000+', communityTrust: 72, expertTrust: 90, regulated: true, regulators: ['SAMA'] },
  

  // Qatar & Kuwait
  { id: 'qnb', name: 'Qatar National Bank', logo: 'https://logo.clearbit.com/qnb.com', type: 'bank', region: 'middle_east_africa', description: 'Middle East largest bank by assets.', founded: '1964', headquarters: 'Doha, Qatar', aum: '$350B', employees: '28,000+', communityTrust: 80, expertTrust: 88, regulated: true, regulators: ['QCB'] },
  { id: 'qia', name: 'Qatar Investment Authority', logo: 'https://logo.clearbit.com/qia.qa', type: 'pension_fund', region: 'middle_east_africa', description: 'Qatar sovereign wealth fund.', founded: '2005', headquarters: 'Doha, Qatar', aum: '$475B', employees: '500+', communityTrust: 76, expertTrust: 90, regulated: true, regulators: ['QCB'] },
  { id: 'kia', name: 'Kuwait Investment Authority', logo: 'https://logo.clearbit.com/kia.gov.kw', type: 'pension_fund', region: 'middle_east_africa', description: 'World oldest sovereign wealth fund.', founded: '1953', headquarters: 'Kuwait City, Kuwait', aum: '$800B', employees: '600+', communityTrust: 78, expertTrust: 92, regulated: true, regulators: ['CBK'] },
  { id: 'nbk', name: 'National Bank of Kuwait', logo: 'https://logo.clearbit.com/nbk.com', type: 'bank', region: 'middle_east_africa', description: 'Kuwait largest bank.', founded: '1952', headquarters: 'Kuwait City, Kuwait', aum: '$120B', employees: '10,000+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['CBK'] },

  // South Africa
  { id: 'standard-bank', name: 'Standard Bank', logo: 'https://logo.clearbit.com/standardbank.com', type: 'bank', region: 'middle_east_africa', description: 'Africa largest bank by assets.', founded: '1862', headquarters: 'Johannesburg, South Africa', aum: '$150B', employees: '50,000+', communityTrust: 76, expertTrust: 84, regulated: true, regulators: ['SARB'] },
  { id: 'firstrand', name: 'FirstRand', logo: 'https://logo.clearbit.com/firstrand.co.za', type: 'bank', region: 'middle_east_africa', description: 'South African financial services group.', founded: '1998', headquarters: 'Johannesburg, South Africa', aum: '$100B', employees: '45,000+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['SARB'] },
  { id: 'absa', name: 'Absa Group', logo: 'https://logo.clearbit.com/absa.africa', type: 'bank', region: 'middle_east_africa', description: 'African financial services group.', founded: '2018', headquarters: 'Johannesburg, South Africa', aum: '$80B', employees: '33,000+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['SARB'] },
  { id: 'nedbank', name: 'Nedbank', logo: 'https://logo.clearbit.com/nedbank.co.za', type: 'bank', region: 'middle_east_africa', description: 'South African bank.', founded: '1888', headquarters: 'Johannesburg, South Africa', aum: '$70B', employees: '28,000+', communityTrust: 76, expertTrust: 80, regulated: true, regulators: ['SARB'] },
  
  { id: 'pic', name: 'Public Investment Corporation', logo: 'https://logo.clearbit.com/pic.gov.za', type: 'pension_fund', region: 'middle_east_africa', description: 'Africa largest asset manager.', founded: '2004', headquarters: 'Pretoria, South Africa', aum: '$170B', employees: '400+', communityTrust: 72, expertTrust: 82, regulated: true, regulators: ['FSCA'] },
  { id: 'coronation', name: 'Coronation Fund Managers', logo: 'https://logo.clearbit.com/coronation.com', type: 'asset_manager', region: 'middle_east_africa', description: 'South African asset manager.', founded: '1993', headquarters: 'Cape Town, South Africa', aum: '$50B', employees: '300+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['FSCA'] },
  { id: 'allan-gray', name: 'Allan Gray', logo: 'https://logo.clearbit.com/allangray.co.za', type: 'asset_manager', region: 'middle_east_africa', description: 'South African investment manager.', founded: '1973', headquarters: 'Cape Town, South Africa', aum: '$40B', employees: '400+', communityTrust: 82, expertTrust: 86, regulated: true, regulators: ['FSCA'] },

  // ===== LATIN AMERICA =====
  // Brazil
  { id: 'itau', name: 'Itaú Unibanco', logo: 'https://logo.clearbit.com/itau.com.br', type: 'bank', region: 'latin_america', description: 'Brazil largest private bank.', founded: '2008', headquarters: 'São Paulo, Brazil', aum: '$450B', employees: '97,000+', communityTrust: 78, expertTrust: 88, regulated: true, regulators: ['BCB', 'CVM'] },
  { id: 'bradesco', name: 'Banco Bradesco', logo: 'https://logo.clearbit.com/bradesco.com.br', type: 'bank', region: 'latin_america', description: 'Brazil second largest private bank.', founded: '1943', headquarters: 'Osasco, Brazil', aum: '$380B', employees: '86,000+', communityTrust: 76, expertTrust: 86, regulated: true, regulators: ['BCB', 'CVM'] },
  { id: 'banco-do-brasil', name: 'Banco do Brasil', logo: 'https://logo.clearbit.com/bb.com.br', type: 'bank', region: 'latin_america', description: 'Brazil largest bank by assets.', founded: '1808', headquarters: 'Brasília, Brazil', aum: '$420B', employees: '85,000+', communityTrust: 74, expertTrust: 84, regulated: true, regulators: ['BCB', 'CVM'] },
  { id: 'btg', name: 'BTG Pactual', logo: 'https://logo.clearbit.com/btgpactual.com', type: 'bank', region: 'latin_america', description: 'Latin America largest investment bank.', founded: '1983', headquarters: 'São Paulo, Brazil', aum: '$300B', employees: '7,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['BCB', 'CVM'] },
  { id: 'xp', name: 'XP Inc.', logo: 'https://logo.clearbit.com/xpinc.com', type: 'broker', region: 'latin_america', description: 'Brazil largest independent broker.', founded: '2001', headquarters: 'São Paulo, Brazil', employees: '6,500+', communityTrust: 80, expertTrust: 82, regulated: true, regulators: ['CVM'] },
  { id: 'nubank', name: 'Nubank', logo: 'https://logo.clearbit.com/nubank.com.br', type: 'bank', region: 'latin_america', description: 'World largest digital bank by customers.', founded: '2013', headquarters: 'São Paulo, Brazil', employees: '7,000+', communityTrust: 84, expertTrust: 80, regulated: true, regulators: ['BCB'] },
  

  // Mexico
  { id: 'banorte', name: 'Banorte', logo: 'https://logo.clearbit.com/banorte.com', type: 'bank', region: 'latin_america', description: 'Mexico largest Mexican-owned bank.', founded: '1899', headquarters: 'Monterrey, Mexico', aum: '$100B', employees: '28,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['CNBV'] },
  { id: 'bbva-mexico', name: 'BBVA México', logo: 'https://logo.clearbit.com/bbva.mx', type: 'bank', region: 'latin_america', description: 'Mexico largest bank by assets.', founded: '1932', headquarters: 'Mexico City, Mexico', aum: '$150B', employees: '38,000+', communityTrust: 74, expertTrust: 84, regulated: true, regulators: ['CNBV'] },
  
  { id: 'gbm', name: 'GBM', logo: 'https://logo.clearbit.com/gbm.com', type: 'broker', region: 'latin_america', description: 'Mexico largest brokerage firm.', founded: '1983', headquarters: 'Mexico City, Mexico', employees: '1,500+', communityTrust: 76, expertTrust: 80, regulated: true, regulators: ['CNBV'] },

  // Colombia, Chile, Peru, Argentina
  { id: 'grupo-aval', name: 'Grupo Aval', type: 'bank', region: 'latin_america', description: 'Colombia largest financial group.', founded: '1998', headquarters: 'Bogotá, Colombia', aum: '$80B', employees: '80,000+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['Superfinanciera'] },
  { id: 'bancolombia', name: 'Bancolombia', type: 'bank', region: 'latin_america', description: 'Colombia largest bank.', founded: '1875', headquarters: 'Medellín, Colombia', aum: '$90B', employees: '32,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['Superfinanciera'] },
  
  { id: 'banco-de-chile', name: 'Banco de Chile', type: 'bank', region: 'latin_america', description: 'Chile major bank.', founded: '1893', headquarters: 'Santiago, Chile', aum: '$60B', employees: '13,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['CMF Chile'] },
  { id: 'bci', name: 'Banco de Crédito e Inversiones', type: 'bank', region: 'latin_america', description: 'Chilean bank.', founded: '1937', headquarters: 'Santiago, Chile', aum: '$50B', employees: '12,000+', communityTrust: 76, expertTrust: 80, regulated: true, regulators: ['CMF Chile'] },
  
  { id: 'afp-capital', name: 'AFP Capital', type: 'pension_fund', region: 'latin_america', description: 'Chilean pension fund.', founded: '1980', headquarters: 'Santiago, Chile', aum: '$45B', employees: '800+', communityTrust: 72, expertTrust: 78, regulated: true, regulators: ['SP Chile'] },
  { id: 'credicorp', name: 'Credicorp', type: 'bank', region: 'latin_america', description: 'Peru largest financial services.', founded: '1995', headquarters: 'Lima, Peru', aum: '$70B', employees: '40,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['SBS'] },
  
  
  { id: 'banco-galicia', name: 'Banco Galicia', type: 'bank', region: 'latin_america', description: 'Major Argentine bank.', founded: '1905', headquarters: 'Buenos Aires, Argentina', aum: '$20B', employees: '7,000+', communityTrust: 72, expertTrust: 76, regulated: true, regulators: ['BCRA'] },

  // ===== GLOBAL / MULTI-REGIONAL =====
  { id: 'grayscale', name: 'Grayscale Investments', type: 'asset_manager', region: 'global', description: 'Crypto asset manager.', founded: '2013', headquarters: 'Stamford, CT', aum: '$35B', employees: '200+', communityTrust: 74, expertTrust: 78, regulated: true, regulators: ['SEC'] },
  { id: 'galaxy-digital', name: 'Galaxy Digital', type: 'asset_manager', region: 'global', description: 'Crypto financial services firm.', founded: '2018', headquarters: 'New York, NY', aum: '$5B', employees: '500+', communityTrust: 70, expertTrust: 76, regulated: true, regulators: ['SEC'] },
  { id: 'bitwise', name: 'Bitwise Asset Management', type: 'asset_manager', region: 'global', description: 'Crypto index fund manager.', founded: '2017', headquarters: 'San Francisco, CA', aum: '$4B', employees: '100+', communityTrust: 74, expertTrust: 78, regulated: true, regulators: ['SEC'] },

  // ===== ADDITIONAL USA BROKERS =====
  { id: 'moomoo', name: 'moomoo', type: 'broker', region: 'north_america', description: 'Commission-free trading platform with advanced tools.', founded: '2018', headquarters: 'Palo Alto, CA', employees: '500+', communityTrust: 74, expertTrust: 72, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'lightspeed', name: 'Lightspeed Financial', type: 'broker', region: 'north_america', description: 'Professional trading platform for active traders.', founded: '2006', headquarters: 'New York, NY', employees: '300+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['SEC', 'FINRA'] },
  { id: 'tradier', name: 'Tradier', type: 'broker', region: 'north_america', description: 'Brokerage platform with API access.', founded: '2012', headquarters: 'Charlotte, NC', employees: '100+', communityTrust: 72, expertTrust: 74, regulated: true, regulators: ['SEC', 'FINRA'] },

  // Additional USA Hedge Funds
  { id: 'steadfast', name: 'Steadfast Capital', type: 'hedge_fund', region: 'north_america', description: 'Technology-focused hedge fund.', founded: '2007', headquarters: 'New York, NY', aum: '$15B', employees: '50+', communityTrust: 74, expertTrust: 86, regulated: true, regulators: ['SEC'] },
  { id: 'balyasny', name: 'Balyasny Asset Management', type: 'hedge_fund', region: 'north_america', description: 'Multi-strategy hedge fund.', founded: '2001', headquarters: 'Chicago, IL', aum: '$20B', employees: '1,500+', communityTrust: 72, expertTrust: 84, regulated: true, regulators: ['SEC'] },
  { id: 'farallon', name: 'Farallon Capital', type: 'hedge_fund', region: 'north_america', description: 'Multi-strategy investment firm.', founded: '1986', headquarters: 'San Francisco, CA', aum: '$40B', employees: '200+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['SEC'] },
  { id: 'och-ziff', name: 'Sculptor Capital', type: 'hedge_fund', region: 'north_america', description: 'Multi-strategy alternative manager.', founded: '1994', headquarters: 'New York, NY', aum: '$35B', employees: '400+', communityTrust: 68, expertTrust: 82, regulated: true, regulators: ['SEC'] },
  { id: 'canyon', name: 'Canyon Partners', type: 'hedge_fund', region: 'north_america', description: 'Alternative investment firm.', founded: '1990', headquarters: 'Los Angeles, CA', aum: '$25B', employees: '250+', communityTrust: 74, expertTrust: 86, regulated: true, regulators: ['SEC'] },

  // ===== ADDITIONAL CANADA =====
  { id: 'ci-financial', name: 'CI Financial', type: 'asset_manager', region: 'north_america', description: 'Independent Canadian asset manager.', founded: '1965', headquarters: 'Toronto, Canada', aum: '$400B', employees: '3,500+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['OSC', 'IIROC'] },
  { id: 'agf', name: 'AGF Management', type: 'asset_manager', region: 'north_america', description: 'Canadian investment management firm.', founded: '1957', headquarters: 'Toronto, Canada', aum: '$45B', employees: '500+', communityTrust: 74, expertTrust: 78, regulated: true, regulators: ['OSC'] },
  { id: 'fiera-capital', name: 'Fiera Capital', type: 'asset_manager', region: 'north_america', description: 'Independent Canadian asset manager.', founded: '2003', headquarters: 'Montreal, Canada', aum: '$180B', employees: '850+', communityTrust: 76, expertTrust: 80, regulated: true, regulators: ['OSC', 'AMF'] },
  { id: 'cppib', name: 'CPP Investments', type: 'pension_fund', region: 'north_america', description: 'Canada Pension Plan Investment Board.', founded: '1997', headquarters: 'Toronto, Canada', aum: '$575B', employees: '2,100+', communityTrust: 88, expertTrust: 94, regulated: true, regulators: ['OSFI'] },
  { id: 'otpp', name: 'Ontario Teachers Pension Plan', type: 'pension_fund', region: 'north_america', description: 'Canada largest single-profession pension plan.', founded: '1990', headquarters: 'Toronto, Canada', aum: '$250B', employees: '1,400+', communityTrust: 86, expertTrust: 92, regulated: true, regulators: ['OSFI'] },
  { id: 'caisse', name: 'Caisse de dépôt', type: 'pension_fund', region: 'north_america', description: 'Quebec institutional investor.', founded: '1965', headquarters: 'Montreal, Canada', aum: '$425B', employees: '1,100+', communityTrust: 84, expertTrust: 90, regulated: true, regulators: ['AMF'] },
  { id: 'desjardins', name: 'Desjardins Group', type: 'bank', region: 'north_america', description: 'Largest federation of credit unions in North America.', founded: '1900', headquarters: 'Lévis, Canada', aum: '$420B', employees: '53,000+', communityTrust: 82, expertTrust: 86, regulated: true, regulators: ['AMF'] },
  { id: 'interactive-brokers-canada', name: 'Interactive Brokers Canada', type: 'broker', region: 'north_america', description: 'Canadian arm of IBKR.', founded: '1999', headquarters: 'Montreal, Canada', employees: '200+', communityTrust: 88, expertTrust: 90, regulated: true, regulators: ['IIROC', 'CIPF'] },
  { id: 'nbcn', name: 'National Bank Direct Brokerage', type: 'broker', region: 'north_america', description: 'Online brokerage by National Bank.', founded: '2000', headquarters: 'Montreal, Canada', employees: '300+', communityTrust: 76, expertTrust: 78, regulated: true, regulators: ['IIROC', 'CIPF'] },

  // ===== ADDITIONAL SINGAPORE =====
  { id: 'fullerton', name: 'Fullerton Fund Management', type: 'asset_manager', region: 'asia_pacific', description: 'Singapore institutional asset manager.', founded: '2003', headquarters: 'Singapore', aum: '$65B', employees: '200+', communityTrust: 80, expertTrust: 86, regulated: true, regulators: ['MAS'] },
  { id: 'nikko-am-singapore', name: 'Nikko Asset Management Asia', type: 'asset_manager', region: 'asia_pacific', description: 'Asian arm of Nikko AM.', founded: '2005', headquarters: 'Singapore', aum: '$30B', employees: '150+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['MAS'] },
  { id: 'eastspring', name: 'Eastspring Investments', type: 'asset_manager', region: 'asia_pacific', description: 'Asian asset management arm of Prudential.', founded: '1994', headquarters: 'Singapore', aum: '$250B', employees: '600+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['MAS'] },
  { id: 'moomoo-sg', name: 'moomoo Singapore', type: 'broker', region: 'asia_pacific', description: 'Digital trading platform for Singapore investors.', founded: '2020', headquarters: 'Singapore', employees: '100+', communityTrust: 74, expertTrust: 72, regulated: true, regulators: ['MAS'] },
  { id: 'saxo-singapore', name: 'Saxo Markets Singapore', type: 'broker', region: 'asia_pacific', description: 'Multi-asset trading platform.', founded: '2006', headquarters: 'Singapore', employees: '150+', communityTrust: 78, expertTrust: 82, regulated: true, regulators: ['MAS'] },
  { id: 'cgsi', name: 'CGS-CIMB Securities', type: 'broker', region: 'asia_pacific', description: 'Joint venture brokerage in Singapore.', founded: '2018', headquarters: 'Singapore', employees: '300+', communityTrust: 72, expertTrust: 76, regulated: true, regulators: ['MAS'] },

  // ===== ADDITIONAL CHINA (Mainland) =====
  { id: 'icbc', name: 'Industrial and Commercial Bank of China', type: 'bank', region: 'asia_pacific', description: 'World largest bank by total assets.', founded: '1984', headquarters: 'Beijing, China', aum: '$5.5T', employees: '435,000+', communityTrust: 76, expertTrust: 88, regulated: true, regulators: ['CBIRC', 'PBOC'] },
  { id: 'ccb', name: 'China Construction Bank', type: 'bank', region: 'asia_pacific', description: 'Second largest bank in China.', founded: '1954', headquarters: 'Beijing, China', aum: '$4.7T', employees: '349,000+', communityTrust: 74, expertTrust: 86, regulated: true, regulators: ['CBIRC', 'PBOC'] },
  { id: 'abc', name: 'Agricultural Bank of China', type: 'bank', region: 'asia_pacific', description: 'Third largest bank in China.', founded: '1951', headquarters: 'Beijing, China', aum: '$4.5T', employees: '461,000+', communityTrust: 72, expertTrust: 84, regulated: true, regulators: ['CBIRC', 'PBOC'] },
  { id: 'boc', name: 'Bank of China', type: 'bank', region: 'asia_pacific', description: 'Fourth largest bank in China.', founded: '1912', headquarters: 'Beijing, China', aum: '$4.0T', employees: '310,000+', communityTrust: 74, expertTrust: 86, regulated: true, regulators: ['CBIRC', 'PBOC'] },
  { id: 'bocom', name: 'Bank of Communications', type: 'bank', region: 'asia_pacific', description: 'Fifth largest bank in China.', founded: '1908', headquarters: 'Shanghai, China', aum: '$1.8T', employees: '93,000+', communityTrust: 72, expertTrust: 82, regulated: true, regulators: ['CBIRC', 'PBOC'] },
  { id: 'cmb', name: 'China Merchants Bank', type: 'bank', region: 'asia_pacific', description: 'Leading Chinese commercial bank.', founded: '1987', headquarters: 'Shenzhen, China', aum: '$1.4T', employees: '115,000+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['CBIRC'] },
  { id: 'citic-securities', name: 'CITIC Securities', type: 'broker', region: 'asia_pacific', description: 'China largest securities broker.', founded: '1995', headquarters: 'Beijing, China', employees: '20,000+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['CSRC'] },
  { id: 'huatai', name: 'Huatai Securities', type: 'broker', region: 'asia_pacific', description: 'Major Chinese securities company.', founded: '1991', headquarters: 'Nanjing, China', employees: '15,000+', communityTrust: 74, expertTrust: 80, regulated: true, regulators: ['CSRC'] },
  { id: 'china-amc', name: 'China Asset Management', type: 'asset_manager', region: 'asia_pacific', description: 'One of China largest asset managers.', founded: '1998', headquarters: 'Beijing, China', aum: '$200B', employees: '800+', communityTrust: 76, expertTrust: 82, regulated: true, regulators: ['CSRC'] },
  { id: 'e-fund', name: 'E Fund Management', type: 'asset_manager', region: 'asia_pacific', description: 'Leading Chinese mutual fund company.', founded: '2001', headquarters: 'Guangzhou, China', aum: '$180B', employees: '600+', communityTrust: 78, expertTrust: 84, regulated: true, regulators: ['CSRC'] },
  { id: 'cic', name: 'China Investment Corporation', type: 'pension_fund', region: 'asia_pacific', description: 'China sovereign wealth fund.', founded: '2007', headquarters: 'Beijing, China', aum: '$1.2T', employees: '800+', communityTrust: 72, expertTrust: 90, regulated: true, regulators: ['MOF'] },
  { id: 'futu', name: 'Futu Holdings', type: 'broker', region: 'asia_pacific', description: 'Chinese online brokerage (Moomoo parent).', founded: '2012', headquarters: 'Shenzhen, China', employees: '3,500+', communityTrust: 76, expertTrust: 74, regulated: true, regulators: ['CSRC', 'SEC'] },
  { id: 'tiger-securities', name: 'UP Fintech (Tiger Brokers)', type: 'broker', region: 'asia_pacific', description: 'Chinese cross-border online broker.', founded: '2014', headquarters: 'Beijing, China', employees: '1,500+', communityTrust: 72, expertTrust: 70, regulated: true, regulators: ['CSRC', 'SEC'] },

  // ===== BANKS (YOUNG) =====
  { id: 'varo', name: 'Varo Bank', logo: 'https://logo.clearbit.com/varo.com', type: 'bank', region: 'north_america', description: 'First mobile-only national bank in the US with no-fee banking.', founded: '2017', headquarters: 'San Francisco, CA', employees: '700+', communityTrust: 72, expertTrust: 70, regulated: true, regulators: ['FDIC', 'OCC'] },
  { id: 'hmbradley', name: 'HMBradley', logo: 'https://logo.clearbit.com/hmbradley.com', type: 'bank', region: 'north_america', description: 'Tiered savings account with up to 3% APY based on savings habits.', founded: '2019', headquarters: 'Los Angeles, CA', employees: '100+', communityTrust: 70, expertTrust: 68, regulated: true, regulators: ['FDIC'] },
  { id: 'mercury', name: 'Mercury', logo: 'https://logo.clearbit.com/mercury.com', type: 'bank', region: 'north_america', description: 'Business banking platform designed for startups and tech companies.', founded: '2019', headquarters: 'San Francisco, CA', employees: '850+', communityTrust: 76, expertTrust: 74, regulated: true, regulators: ['FDIC'] },

  // ===== LOW-RATED BROKERS AND INVESTMENT COMPANIES (20-60 Trust Score) =====
  { id: 'fxcm', name: 'FXCM', logo: 'https://logo.clearbit.com/fxcm.com', type: 'broker', region: 'global', description: 'Forex broker with regulatory issues and customer complaints.', founded: '1999', headquarters: 'London, UK', employees: '400+', communityTrust: 45, expertTrust: 38, regulated: false, website: 'https://www.fxcm.com' },
  { id: 'alpari', name: 'Alpari', logo: 'https://logo.clearbit.com/alpari.com', type: 'broker', region: 'global', description: 'Forex broker with multiple regulatory violations and client fund issues.', founded: '1998', headquarters: 'Moscow, Russia', employees: '300+', communityTrust: 35, expertTrust: 28, regulated: false, website: 'https://alpari.com' },
  { id: 'instaforex', name: 'InstaForex', logo: 'https://logo.clearbit.com/instaforex.com', type: 'broker', region: 'global', description: 'Offshore forex broker with numerous withdrawal complaints.', founded: '2007', headquarters: 'Kingstown, Saint Vincent', employees: '200+', communityTrust: 42, expertTrust: 35, regulated: false, website: 'https://www.instaforex.com' },
  { id: 'exness', name: 'Exness', logo: 'https://logo.clearbit.com/exness.com', type: 'broker', region: 'global', description: 'Forex broker with aggressive marketing and questionable practices.', founded: '2008', headquarters: 'Limassol, Cyprus', employees: '2,000+', communityTrust: 48, expertTrust: 40, regulated: true, regulators: ['CySEC'], website: 'https://www.exness.com' },
  { id: 'xm-group', name: 'XM Group', logo: 'https://logo.clearbit.com/xm.com', type: 'broker', region: 'global', description: 'Forex broker with mixed reviews and regulatory concerns.', founded: '2009', headquarters: 'Limassol, Cyprus', employees: '1,000+', communityTrust: 52, expertTrust: 45, regulated: true, regulators: ['CySEC'], website: 'https://www.xm.com' },
  { id: 'hotforex', name: 'HotForex', logo: 'https://logo.clearbit.com/hotforex.com', type: 'broker', region: 'global', description: 'Forex broker with offshore regulation and customer complaints.', founded: '2010', headquarters: 'Port Louis, Mauritius', employees: '500+', communityTrust: 44, expertTrust: 38, regulated: true, regulators: ['FSC'], website: 'https://www.hotforex.com' },
  { id: 'fxpro', name: 'FxPro', logo: 'https://logo.clearbit.com/fxpro.com', type: 'broker', region: 'global', description: 'Forex broker with execution issues and slippage complaints.', founded: '2006', headquarters: 'Limassol, Cyprus', employees: '800+', communityTrust: 56, expertTrust: 50, regulated: true, regulators: ['CySEC', 'FCA'], website: 'https://www.fxpro.com' },
  { id: 'tickmill', name: 'Tickmill', logo: 'https://logo.clearbit.com/tickmill.com', type: 'broker', region: 'global', description: 'Forex broker with limited regulation and transparency issues.', founded: '2014', headquarters: 'London, UK', employees: '150+', communityTrust: 58, expertTrust: 52, regulated: true, regulators: ['FCA'], website: 'https://www.tickmill.com' },
  { id: 'ic-markets', name: 'IC Markets', logo: 'https://logo.clearbit.com/icmarkets.com', type: 'broker', region: 'global', description: 'Forex broker with spread manipulation allegations.', founded: '2007', headquarters: 'Sydney, Australia', employees: '600+', communityTrust: 54, expertTrust: 48, regulated: true, regulators: ['ASIC'], website: 'https://www.icmarkets.com' },
  { id: 'pepperstone', name: 'Pepperstone', logo: 'https://logo.clearbit.com/pepperstone.com', type: 'broker', region: 'global', description: 'Forex broker with execution delays during volatile markets.', founded: '2010', headquarters: 'Melbourne, Australia', employees: '800+', communityTrust: 60, expertTrust: 55, regulated: true, regulators: ['ASIC', 'FCA'], website: 'https://www.pepperstone.com' },
  { id: 'oanda', name: 'OANDA', logo: 'https://logo.clearbit.com/oanda.com', type: 'broker', region: 'global', description: 'Forex broker with spread widening and execution issues.', founded: '1996', headquarters: 'Toronto, Canada', employees: '600+', communityTrust: 58, expertTrust: 52, regulated: true, regulators: ['CFTC', 'NFA'], website: 'https://www.oanda.com' },
  { id: 'forex-com', name: 'FOREX.com', logo: 'https://logo.clearbit.com/forex.com', type: 'broker', region: 'global', description: 'Forex broker with platform stability issues and customer service problems.', founded: '2001', headquarters: 'Bedminster, NJ', employees: '500+', communityTrust: 55, expertTrust: 50, regulated: true, regulators: ['CFTC', 'NFA'], website: 'https://www.forex.com' },
  { id: 'plus500', name: 'Plus500', logo: 'https://logo.clearbit.com/plus500.com', type: 'broker', region: 'global', description: 'CFD broker with aggressive marketing and high-risk products.', founded: '2008', headquarters: 'Haifa, Israel', employees: '500+', communityTrust: 46, expertTrust: 40, regulated: true, regulators: ['FCA', 'CySEC'], website: 'https://www.plus500.com' },
  { id: 'etoro', name: 'eToro', logo: 'https://logo.clearbit.com/etoro.com', type: 'broker', region: 'global', description: 'Social trading platform with withdrawal issues and high spreads.', founded: '2007', headquarters: 'Limassol, Cyprus', employees: '1,800+', communityTrust: 50, expertTrust: 45, regulated: true, regulators: ['CySEC', 'FCA'], website: 'https://www.etoro.com' },
  { id: 'avatrade', name: 'AvaTrade', logo: 'https://logo.clearbit.com/avatrade.com', type: 'broker', region: 'global', description: 'Forex broker with regulatory warnings and customer complaints.', founded: '2006', headquarters: 'Dublin, Ireland', employees: '400+', communityTrust: 48, expertTrust: 42, regulated: true, regulators: ['CBI'], website: 'https://www.avatrade.com' },
  { id: 'roboforex', name: 'RoboForex', logo: 'https://logo.clearbit.com/roboforex.com', type: 'broker', region: 'global', description: 'Forex broker with bonus abuse policies and withdrawal restrictions.', founded: '2009', headquarters: 'Belize City, Belize', employees: '200+', communityTrust: 40, expertTrust: 34, regulated: true, regulators: ['IFSC'], website: 'https://www.roboforex.com' },
  { id: 'justforex', name: 'JustForex', logo: 'https://logo.clearbit.com/justforex.com', type: 'broker', region: 'global', description: 'Forex broker with suspicious bonus offers and regulatory concerns.', founded: '2012', headquarters: 'Kingstown, Saint Vincent', employees: '100+', communityTrust: 35, expertTrust: 28, regulated: false, website: 'https://justforex.com' },
  { id: 'tradersway', name: 'TradersWay', logo: 'https://logo.clearbit.com/tradersway.com', type: 'broker', region: 'global', description: 'Forex broker with offshore registration and limited protection.', founded: '2011', headquarters: 'Kingstown, Saint Vincent', employees: '50+', communityTrust: 38, expertTrust: 32, regulated: false, website: 'https://www.tradersway.com' },
  { id: 'fxchoice', name: 'FXChoice', logo: 'https://logo.clearbit.com/fxchoice.com', type: 'broker', region: 'global', description: 'Forex broker with Belize regulation and customer complaints.', founded: '2010', headquarters: 'Belize City, Belize', employees: '50+', communityTrust: 41, expertTrust: 35, regulated: true, regulators: ['IFSC'], website: 'https://www.fxchoice.com' },
  { id: 'libertex', name: 'Libertex', logo: 'https://logo.clearbit.com/libertex.com', type: 'broker', region: 'global', description: 'CFD broker with high leverage risks and customer complaints.', founded: '1997', headquarters: 'Limassol, Cyprus', employees: '300+', communityTrust: 48, expertTrust: 42, regulated: true, regulators: ['CySEC'], website: 'https://www.libertex.com' },
  { id: 'admiral-markets', name: 'Admiral Markets', logo: 'https://logo.clearbit.com/admiralmarkets.com', type: 'broker', region: 'global', description: 'Forex broker with execution delays and slippage issues.', founded: '2001', headquarters: 'Tallinn, Estonia', employees: '400+', communityTrust: 56, expertTrust: 50, regulated: true, regulators: ['FCA'], website: 'https://www.admiralmarkets.com' },
  { id: 'fxtm', name: 'FXTM', logo: 'https://logo.clearbit.com/forextime.com', type: 'broker', region: 'global', description: 'Forex broker with bonus abuse policies and withdrawal restrictions.', founded: '2011', headquarters: 'Limassol, Cyprus', employees: '400+', communityTrust: 52, expertTrust: 46, regulated: true, regulators: ['CySEC'], website: 'https://www.forextime.com' },
  { id: 'octafx', name: 'OctaFX', logo: 'https://logo.clearbit.com/octafx.com', type: 'broker', region: 'global', description: 'Forex broker with offshore regulation and customer service issues.', founded: '2011', headquarters: 'Kingstown, Saint Vincent', employees: '200+', communityTrust: 44, expertTrust: 38, regulated: false, website: 'https://www.octafx.com' },
  { id: 'fp-markets', name: 'FP Markets', logo: 'https://logo.clearbit.com/fpmarkets.com', type: 'broker', region: 'global', description: 'Forex broker with execution issues and customer service problems.', founded: '2005', headquarters: 'Sydney, Australia', employees: '300+', communityTrust: 55, expertTrust: 49, regulated: true, regulators: ['ASIC'], website: 'https://www.fpmarkets.com' },
  { id: 'easymarkets', name: 'EasyMarkets', logo: 'https://logo.clearbit.com/easymarkets.com', type: 'broker', region: 'global', description: 'Forex broker with execution issues and customer service problems.', founded: '2001', headquarters: 'Limassol, Cyprus', employees: '200+', communityTrust: 52, expertTrust: 46, regulated: true, regulators: ['CySEC'], website: 'https://www.easymarkets.com' },
  { id: 'hycm', name: 'HYCM', logo: 'https://logo.clearbit.com/hycm.com', type: 'broker', region: 'global', description: 'Forex broker with execution issues and customer service problems.', founded: '1977', headquarters: 'Limassol, Cyprus', employees: '200+', communityTrust: 54, expertTrust: 48, regulated: true, regulators: ['CySEC', 'FCA'], website: 'https://www.hycm.com' },
  { id: 'trading-212', name: 'Trading 212', logo: 'https://logo.clearbit.com/trading212.com', type: 'broker', region: 'global', description: 'CFD broker with execution issues and platform restrictions.', founded: '2004', headquarters: 'London, UK', employees: '700+', communityTrust: 54, expertTrust: 48, regulated: true, regulators: ['FCA'], website: 'https://www.trading212.com' },
  { id: 'axitrader', name: 'AxiTrader', logo: 'https://logo.clearbit.com/axitrader.com', type: 'broker', region: 'global', description: 'Forex broker with execution delays and slippage issues.', founded: '2007', headquarters: 'Sydney, Australia', employees: '300+', communityTrust: 56, expertTrust: 50, regulated: true, regulators: ['ASIC'], website: 'https://www.axitrader.com' },
  { id: 'vantage-fx', name: 'Vantage FX', logo: 'https://logo.clearbit.com/vantagefx.com', type: 'broker', region: 'global', description: 'Forex broker with platform issues and customer complaints.', founded: '2009', headquarters: 'Sydney, Australia', employees: '200+', communityTrust: 54, expertTrust: 48, regulated: true, regulators: ['ASIC'], website: 'https://www.vantagefx.com' },
  { id: 'titan-fx', name: 'Titan FX', logo: 'https://logo.clearbit.com/titanfx.com', type: 'broker', region: 'global', description: 'Forex broker with limited regulation and transparency concerns.', founded: '2014', headquarters: 'Auckland, New Zealand', employees: '100+', communityTrust: 48, expertTrust: 42, regulated: true, regulators: ['FMA'], website: 'https://www.titanfx.com' },
];

export const organizationTypes: { value: OrganizationType | 'all'; label: string }[] = [
  { value: 'all', label: 'All Types' },
  { value: 'broker', label: 'Brokers' },
  { value: 'hedge_fund', label: 'Hedge Funds' },
  { value: 'asset_manager', label: 'Asset Managers' },
  { value: 'bank', label: 'Banks' },
  { value: 'wealth_manager', label: 'Wealth Managers' },
  { value: 'pension_fund', label: 'Pension Funds' },
];

export const regions: { value: Region | 'all'; label: string }[] = [
  { value: 'all', label: 'All Regions' },
  { value: 'north_america', label: 'North America' },
  { value: 'europe', label: 'Europe' },
  { value: 'asia_pacific', label: 'Asia Pacific' },
  { value: 'middle_east_africa', label: 'Middle East & Africa' },
  { value: 'latin_america', label: 'Latin America' },
  { value: 'global', label: 'Global' },
];

export function getOrganizationsByType(type?: OrganizationType | 'all'): Organization[] {
  if (!type || type === 'all') return organizations;
  return organizations.filter(org => org.type === type);
}

export function getOrganizationsByRegion(region?: Region | 'all'): Organization[] {
  if (!region || region === 'all') return organizations;
  return organizations.filter(org => org.region === region);
}

export function filterOrganizations(type?: OrganizationType | 'all', region?: Region | 'all'): Organization[] {
  let filtered = organizations;
  if (type && type !== 'all') {
    filtered = filtered.filter(org => org.type === type);
  }
  if (region && region !== 'all') {
    filtered = filtered.filter(org => org.region === region);
  }
  return filtered;
}

export function sortByTrust(orgs: Organization[], sortBy: 'combined' | 'community' | 'expert' = 'combined'): Organization[] {
  return [...orgs].sort((a, b) => {
    if (sortBy === 'community') return b.communityTrust - a.communityTrust;
    if (sortBy === 'expert') return b.expertTrust - a.expertTrust;
    const aScore = (a.communityTrust + a.expertTrust) / 2;
    const bScore = (b.communityTrust + b.expertTrust) / 2;
    return bScore - aScore;
  });
}
